### PR TITLE
Update ip-ranges.md

### PR DESCRIPTION
**Pull request by devinmarieb**
# Description
Remove info about IP ranges being in preview.

# Reasons
IP ranges are no longer in preview.

### CODE REVIEW

**Comment by devinmarieb** [comment]
@sebastian-lerner I saw someone mention this in Slack, so I've removed the language around preview/performance plan and moved the note about pricing to the overview section.

**Comment by sebastian-lerner** [comment]
i thought i removed the language about preview yesterday? and it is still only available to perf and Scale plans so we should leave that in. 

we shouldn't say "pricing will be calculated", we should say "pricing is calculated"

**Comment by devinmarieb** [comment]
@sebastian-lerner I didn't see an open PR for this page yet. Possible I missed it. I'll take another look.

**Comment by sebastian-lerner** [comment]
we merged it yesterday https://github.com/circleci/circleci-docs/pull/6311

**Comment by devinmarieb** [comment]
@sebastian-lerner ah nice thanks! nevermind then :)

**Pull request closed without merging**
