### PR TITLE
Update arm-resources.md

### PR DESCRIPTION
**Pull request by sebastian-lerner**
custom should be specified as available for arm.large

# Description
A brief description of the changes.

# Reasons
A link to a GitHub and/or JIRA issue (if applicable).
Otherwise, a brief sentence about why you made these changes.

### CODE REVIEW

**Comment by sebastian-lerner** [comment]
does someone get auto-added to this to review?

**Comment by sebastian-lerner** [comment]
before merging this, is there any guidance on including "Custom" as a "Requisite Plan" option even though it's not on our pricing page?  In general, should we avoid "Requisite Plan" sections or no?

**Review by teesloane — APPROVED** [review]
@sebastian-lerner - I think this change is all good re: differences to pricing page; we're already using "custom" in the line above, and I think it's okay to leave the requisite plan section.

**Comment by sebastian-lerner** [comment]
@teesloane sounds good, I don't think I can actually merge.  Any chance you can merge for me?

**Pull request merged**
