### PR TITLE
Add note that Redis is not started on Ubuntu 14.04

### PR DESCRIPTION
**Pull request by ligaz**

### CODE REVIEW

**Comment by zzak** [comment]
I think this is information is too version specific to go here, what about the other services listed and their possible gotchas? It's better to put this kind of information somewhere it can be easily collected and found.

**Comment by ligaz** [comment]
Good point. Maybe we should delete the whole sentence about which services are started by default then?

**Comment by felicianotech** [comment]
@ligaz For now I'd go with that.

**Comment by felicianotech** [comment]
In the mean time, this PR does make an improvement so I'm going to just merge it.

**Pull request merged**
