### PR TITLE
Update Xcode table

### PR DESCRIPTION
**Pull request by BytesGuy**

### CODE REVIEW

**Review by lriverawong — APPROVED** [review]

**Comment by lriverawong** [comment]
Removing the `12.1.0` in favour of patch version `12.1.1`

**Comment by teesloane** [comment]
Thanks for putting up this update! We are currently trying to resolve why our pipelines are not running (and thus we cannot merge). When merging is available, we will merge this.

**Comment by BytesGuy** [comment]
@teesloane Is this still blocked? Thanks!

**Comment by teesloane** [comment]
@BytesGuy Unfortunately, yes. I'll ping you as soon as we get this resolved!

**Pull request merged**
