### PR TITLE
Update sign up copy

### LINKED ISSUE #2651: Left nav moves off screen when scrolling on sign up page
As soon as I scroll in Chrome on this page https://circleci.com/docs/2.0/first-steps/ the left nav flys out of view (up)

screen shot 2018-08-29 at 11 50 08 am

(Also the instructions say Sign Up button - but there is no signup button other than the link in the instructions)

### PR DESCRIPTION
**Pull request by smart-alek**
# Description
Removes reference to nonexistent signup button.

# Reasons
Fixes #2651

### CODE REVIEW

**Comment by smart-alek** [comment]
I prefer the directness of "Go to". "Visit" sounds like a hotel booking. XD

**Comment by michelle-luna** [comment]
If you haven't signed up before, there is a button, that is the reason for this language (it is for a person who hasn't signed up yet).

**Comment by smart-alek** [comment]
@michelle-luna I'm not seeing the button you're talking about. When I open the linked page in an incognito window, this is what I see:

image

**Comment by felicianotech** [comment]
It wouldn't be that page. Open the Doc in Incognito mode or any other Marketing site page.

**Comment by smart-alek** [comment]
@felicianotech @michelle-luna I'm actually noticing a few more inconsistencies that are outside the scope of this PR:

- Neither of the buttons are "Start" buttons. Both begin with "Sign Up"
- Logging in does not change the behavior of this page, but the document mentions logging in by clicking the buttons.

Since this document is the first one in the Introduction, we should probably fix these sooner rather than later. For now, I'll just make tickets so we can capture the work.

**Comment by michelle-luna** [comment]
The button appears when you are on the docs page, so when you are in the docs and you haven't signed up , there is a big green Sign Up button in the upper right. You don't need more tickets for this work. I agree with changing the button names to match whatever they are on the page.

**Pull request merged**
