### PR TITLE
adding jobs to nav

### PR DESCRIPTION
**Pull request by trevor-circleci**
see ticket: https://circleci.atlassian.net/browse/MKTG-729

Adding jobs to the company dropdown in the nav.

### CODE REVIEW

**Comment by trevor-circleci** [comment]
@smart-alek : the jobs dropdown was in the main site's nav, but not on docs. If you look at the code, on this pr, it's an addition.

**Comment by smart-alek** [comment]
Ah ok, so why do you have to update in two places for the main nav in docs if it's already in the footer? And why do docs not inherit the same main nav as the rest of the site?

**Comment by trevor-circleci** [comment]
Because docs is hosted on a separate site from outer, and it turned out to be a non trivial thing to share a component across servers on a flatfile system. 

and the footer is a whole different element - so it needs to be updated separately.

**Comment by smart-alek** [comment]
Ha, gross. Thanks for the details @trevor-circleci  :shipit:

**Pull request merged**
