### PR TITLE
Fix typo in folder name

### PR DESCRIPTION
**Pull request by buger**

### CODE REVIEW

**Comment by felicianotech** [comment]
https://discuss.circleci.com/t/golang-not-working-as-documented/10261

**Comment by buger** [comment]
Ha, it was not me, but timing is nice :)

**Comment by felicianotech** [comment]
For Ubuntu 14.04, the current doc is correct. For example:

```
ubuntu@box81:~$ ls -lah ~/.go_project/src/github.com/felicianotech/
total 4.0K
drwxrwxr-x 1 ubuntu ubuntu 30 Feb 16 16:49 .
drwxrwxr-x 1 ubuntu ubuntu 26 Feb 16 16:49 ..
lrwxrwxrwx 1 ubuntu ubuntu 28 Feb 16 16:49 cci-testing-pub -> /home/ubuntu/cci-testing-pub
```

Are you seeming something different? Using 12.04 maybe?

**Comment by buger** [comment]
Nope, I'm using 14.04. Just logged via SSH to latest build, here is ls output: 

```
ubuntu@box2584:~$ ls -a -l | grep go
-rw-r--r-- 1 ubuntu ubuntu  220 Apr  9  2014 .bash_logout
drwxr-xr-x 1 ubuntu ubuntu    0 Jan 13 02:02 .go_workspace
```

Note that in all places on the page, except the line I mentioned, always mentioned `.go_workspace` not `.go_projects`.  Here is link to the build itself: https://circleci.com/gh/TykTechnologies/tyk-analytics/60

**Comment by felicianotech** [comment]
Looks like you are overriding the dependencies phase, which is where that symlink would be created. I think that's the issue. I'll verify internally but that might be it.

**Comment by felicianotech** [comment]
So I've verified that that is the issue. Also, I've made a PR to include additional inference information to the Go doc: https://github.com/circleci/circleci-docs/pull/651

**Pull request closed without merging**
