### PR TITLE
Update sidenav.yml

### PR DESCRIPTION
**Pull request by thomasr8**
Made change to link to pipelines from "build processing" to "pipelines."

# Description
A brief description of the changes.

# Reasons
A link to a GitHub and/or JIRA issue (if applicable).
Otherwise, a brief sentence about why you made these changes.

### CODE REVIEW

**Comment by thomasr8** [comment]
This fixes #3852

**Comment by rosieyohannan** [comment]
Not sure about this - I think the build processing doc should still link to the "enabling pipelines' option in the side nav. This new pipelines doc is the one Tyler made to explain the new UI page - I am guessing he and @michelle-luna purposefully didn't add it to the side nav - maybe it's linked to from a blog post or something?

**Comment by thomasr8** [comment]
@rosieyohannan Good point. I will check with @michelle-luna to see if this fix is needed.

**Comment by teesloane** [comment]
Yes, there seems to be a bit of confusion here. We have a few related PR's that need to be sorted out:

From what I can tell, To address #3852 we leave `Enabling Pipelines / build-processing` in the sidebar and merge https://github.com/circleci/circleci-docs/pull/3879 when it's good to go.

**Pull request closed without merging**
