### PR TITLE
[DD-841] Update markdown and adoc files to tag format

### PR DESCRIPTION
**Pull request by chantelle11**
For more information review this file here: https://circleci.atlassian.net/l/cp/qS4Aii6x

# Description
Using a script the markdown and adoc files have been regenerated to the new format.

```
version:
```

Has been replaced with
```
contentTags:
   platform:
```

# Considerations
- Formatting is inconsistent which will be addressed later
Approved formats:
```
contentTags:
  platform:
    - example A
```
```
contentTags:
  platform:
  - example B
```
# Reasons
This will allow for the preparation of using tags in the content.

# Content Checklist
Please follow our style when contributing to CircleCI docs. Our style guide is here: [https://circleci.com/docs/style/style-guide-overview](https://circleci.com/docs/style/style-guide-overview).

Please take a moment to check through the following items when submitting your PR (this is just a guide so will not be relevant for all PRs) 😸:

- [ ] Break up walls of text by adding paragraph breaks.
- [ ] Consider if the content could benefit from more structure, such as lists or tables, to make it easier to consume.
- [ ] Keep the title between 20 and 70 characters.
- [ ] Consider whether the content would benefit from more subsections (h2-h6 headings) to make it easier to consume.
- [ ] Check all headings h1-h6 are in sentence case (only first letter is capitalized).
- [ ] Is there a "Next steps" section at the end of the page giving the reader a clear path to what to read next?
- [ ] Include relevant backlinks to other CircleCI docs/pages.

### CODE REVIEW

**Comment by Mayuko-Sa** [comment]
Hi @chantelle11 would it be possible to change only the English files in this PR? Just wanted to know if both the English and Japanese changes should be done at the same time or it could be done separately. If the latter is possible, the changes wil be pushed from Crowdin about one week later after this PR is merged.

**Review by halie-kastl — APPROVED** [review]
Great work

**Comment by chantelle11** [comment]
> Hi @chantelle11 would it be possible to change only the English files in this PR? Just wanted to know if the English and Japanese changes could be done separately. If it is possible, the changes will be pushed from Crowdin about one week later after this PR is merged.

I can make a PR for just `ja` ^^

**Comment by Mayuko-Sa** [comment]
> I can make a PR for just `ja` ^^

Thank you!!! but I think ja only PR is not necessary, Crowdin creates a PR from this change. By updating only En files I can avoid dealing with 200+ files conflicts manually when merging the next translation PR.

**Review by rsylvian — APPROVED** [review]
Looks good to me ✅ 

Let's make sure we merge https://github.com/circleci/docs-platform/pull/244 before we merge this one, though 🙏

**Pull request merged**
