### PR TITLE
[DD-379] Update Size for Duration and Tag Icons

### PR DESCRIPTION
**Pull request by tshen815**
[Ticket](https://circleci.atlassian.net/browse/DD-396)
[Preview](http://circleci-doc-preview.s3-website-us-east-1.amazonaws.com/update-icons-preview/?force-all)
[Figma](https://www.figma.com/file/HrgpUU2M3ED7OT0p0f99bH/Docs-Disco-Experiments?node-id=4611%3A10926)

**NOTE:** Design review approved by @danbeere 

# Changes

- adjust width and margin for `duration.svg` and `tag.svg`

# Description
Aligning the design of the duration and tag icons closer to the figma mock

# Screenshots
**Before**
Screen Shot 2022-01-31 at 8 15 39 PM
**After:**
Screen Shot 2022-01-31 at 8 15 04 PM

### CODE REVIEW

**Review by chantelle11 — APPROVED** [review]
Thanks for updating this! 💎💕✌️

**Review by nramabad — APPROVED** [review]
I think your before & after pics are swapped.

**Review by rsylvian — CHANGES_REQUESTED** [review]
Looking at Figma vs your implementation it looks like the icons are slightly misaligned (vertically) with the text? It's especially noticeable with the clock icon.

**Comment by tshen815** [comment]
> Looking at Figma vs your implementation it looks like the icons are slightly misaligned (vertically) with the text? It's especially noticeable with the clock icon.

It should be good now, dan will review the preview link for final sign off 👍

**Review by rsylvian — APPROVED** [review]

**Pull request merged**
