### PR TITLE
[CIRCLE-29714] update registry links to devhub

### PR DESCRIPTION
**Pull request by dsayling**
# Description
Mass update the links to the dev hub. Includes a localized update to the links previously not present.

# Reasons
CIRCLE-29714

### CODE REVIEW

**Review by lokst — COMMENTED** [review]
@dsayling Thanks for updating the links! I was wondering if we should not link to the localized pages for now, until we have finished localizations?

**Comment by dsayling** [comment]
Sure thing. We can make a large localization update to the docs when that's complete.

**Review by lokst — APPROVED** [review]
Looks good! I also just realized that it might be better to link to https://circleci.com/developer/orbs rather than https://circleci.com/developer/orbs/ to avoid a redirect, but I don't think it's a blocker since it works either way

**Comment by dsayling** [comment]
Oh I didn't think of that. I just replaced the existing path. I'll make that change too, easy peasy.

**Comment by dsayling** [comment]
I just searched for developer/orbs/[^a-z] and removed the trailing slashes. I think that covers the useages.

**Review by thomasr8 — APPROVED** [review]
Looks good 👍

**Pull request merged**
