### PR TITLE
Should fix the non-escaped link to /docs/configuration#notify

### PR DESCRIPTION
**Pull request by Tzeejay**

### CODE REVIEW

**Comment by Tzeejay** [comment]
Please merge once reviewed. The dead link is present on the live website right now.

**Comment by felicianotech** [comment]
@Tzeejay  I'm not if your fix was the issue though. Did you test it?

**Comment by felicianotech** [comment]
@Tzeejay Yeah this PR published and the issue is still there. I think it's because it's in HTML tags. I typically test things locally to catch these issues. I'll work on a PR right now.

**Comment by felicianotech** [comment]
Kramdown needs to be told to parse markdown within many HTML tags. This was done in #283.

**Pull request merged**
