### PR TITLE
[CIRCLE-24055] Main nav keyboard accessibility

### PR DESCRIPTION
**Pull request by tfe**
**Ticket:** [CIRCLE-24055](https://circleci.atlassian.net/browse/CIRCLE-24055)

This ports over a set of keyboard navigation improvements from circleci.com/outer: https://github.com/circleci/circleci.com/pull/3030.

Changes:
- Turn off autofocus on Algolia search box
- Add nav skip button
- Make items with dropdowns/submenus tabbable
- Make nav bar logo tabbable

### CODE REVIEW

**Comment by janedotbiz** [comment]
I put some comments on the ticket, the side nav keyboardability isn't very usable.

**Comment by tfe** [comment]
Are you saying we shouldn't ship this? Making the side nav accessible seems like a separate concern and shouldn't block the shipping of these improvements, which are significant on their own.

**Comment by janedotbiz** [comment]
I agree, the side nav is/can be a separate issue. 
My main question is, is the search easy _enough_ to get to now that it's not focused first?

**Comment by rosieyohannan** [comment]
Looks good to me, from my limited understanding of the subject :-) Definitely easier to navigate using the keyboard.

**Comment by janedotbiz** [comment]
Oops, didn't mean to re-request review

**Pull request merged**
