### PR TITLE
CIRCLE-5387 External DB Doc

### PR DESCRIPTION
**Pull request by MikeyYeahYeah**
Created a new branch because I butchered the last one 😊 

Original link for archival purposes and a self reminder to be more cautious.
https://github.com/circleci/circleci-docs/pull/884

### CODE REVIEW

**Comment by felicianotech** [comment]
@MikeyYeahYeah You good with this? Ready to merge?

**Comment by ndintenfass** [comment]
@jungziege -- is this the same one you're working on?

**Comment by michelle-luna** [comment]
Not sure if the plan is still to merge this? It looks good to me as well, but wanted to check if we're waiting on something/someone.

**Comment by ndintenfass** [comment]
@michelle-luna leave this for now - it's part of a bigger effort that I need to validate before we merge.

**Comment by ndintenfass** [comment]
@levlaz am I right this can be deleted now? The new HA doc covers this, right?

**Comment by levlaz** [comment]
@ndintenfass correct

**Pull request closed without merging**
