### PR TITLE
Adjust database command

### PR DESCRIPTION
**Pull request by dwightwatson**
First, indicate that the command is only relevant for Laravel (`artisan` is the Laravel command line utility).

Second, the commands can be merged into one using `migrate --seed`.

Third, `--force` will prevent Laravel asking "are you sure" before migrating, and have it just go ahead.

### CODE REVIEW

**Comment by ndintenfass** [comment]
@smart-alek this is perhaps our catalyst for making the configs in docs embedded versions of what's in Github, as accepting this PR (which we should) would make the code in docs different than in the sample project, which would be less than good.

**Comment by smart-alek** [comment]
@ndintenfass yep. Changes to the sample projects should be submitted as PRs in their dedicated repos, and then those changes should propagate to docs.

Either way, thanks for the contrib @dwightwatson! :)

**Comment by felicianotech** [comment]
For the record, the example project was specifically written for Lumen at the time, not Laravel (though they overlap heavily) and PHP in general.

Nathan, I agree.

Alek, we were taking about having the changes go through automatically due to embeds vs having to make these changes in multiple locations.

**Comment by michelle-luna** [comment]
So, is the next step to update this doc with the embed instead?

**Comment by michelle-luna** [comment]
this guide has been reworked for the new demo, so closing this PR now, thank you!

**Pull request closed without merging**
