### PR TITLE
fix: correct link to ubuntu image definition

### PR DESCRIPTION
**Pull request by blimmer**
# Description

The previous link went to an archived repo (https://discuss.circleci.com/tag/machine-images).

# Reasons

This links to the replacement.

# Content Checklist
Please follow our style when contributing to CircleCI docs. Our style guide is here: [https://circleci.com/docs/style/style-guide-overview](https://circleci.com/docs/style/style-guide-overview).

Please take a moment to check through the following items when submitting your PR (this is just a guide so will not be relevant for all PRs) 😸:

- [x] Break up walls of text by adding paragraph breaks.
- [x] Consider if the content could benefit from more structure, such as lists or tables, to make it easier to consume.
- [x] Keep the title between 20 and 70 characters.
- [x] Consider whether the content would benefit from more subsections (h2-h6 headings) to make it easier to consume.
- [x] Check all headings h1-h6 are in sentence case (only first letter is capitalized).
- [x] Is there a "Next steps" section at the end of the page giving the reader a clear path to what to read next?
- [x] Include relevant backlinks to other CircleCI docs/pages.

### CODE REVIEW

**Comment by devinmarieb** [comment]
Hey @blimmer, thanks, but we are no longer maintaining the link you have provided. The current link was a stop-gap for this information. I will double check that there is not a better link to use now though.

**Comment by blimmer** [comment]
@devinmarieb - sounds good. Maybe we just remove this link entirely and rely on the discuss link? https://discuss.circleci.com/tag/machine-images

**Comment by devinmarieb** [comment]
@blimmer Yeah that might be the best course at the moment

**Comment by blimmer** [comment]
Sounds good - updated!

**Review by devinmarieb — APPROVED** [review]

**Comment by devinmarieb** [comment]
@blimmer Thanks! I was also able to track down a command users can run to see what is pre-installed on images they are actively using so I also added that in 👍

**Pull request merged**
