### PR TITLE
[do not merge yet] needs an image update as well

### PR DESCRIPTION
**Pull request by sebastian-lerner**
# Description
A brief description of the changes.

# Reasons
A link to a GitHub and/or JIRA issue (if applicable).
Otherwise, a brief sentence about why you made these changes.

### CODE REVIEW

**Comment by devinmarieb** [comment]
@sebastian-lerner What are we waiting on for the merge? I have the image in another PR.

**Comment by sebastian-lerner** [comment]
@devinmarieb only the image but if you have the updated image already then we're good!

**Review by devinmarieb — APPROVED** [review]

**Comment by sebastian-lerner** [comment]
https://circleci.slack.com/archives/CP4LXVD1T/p1648518006673039

We can update the images now

**Comment by sebastian-lerner** [comment]
Whoops wrong thread

**Comment by Plataformaalgoritmica** [comment]
Hello world.

**Pull request merged**
