### PR TITLE
home page and nav updates

### PR DESCRIPTION
**Pull request by michelle-luna**
# Description
Updates to the home page and navigation based on CPE feedback (to make orbs and images more obvious).

# Reasons
CPE feedback and slightly lower ratings of home page this year compared to last year.

### CODE REVIEW

**Comment by teesloane** [comment]
This looks great and scales nicely on mobile. I noticed there is a bit of text/links in the upper right corner that might need to be moved? 

Screen Shot 2020-08-17 at 9 58 30 AM

**Comment by rosieyohannan** [comment]
Sorry I've not left review comments yet! I have had a look and it looks great to me. Just wanted to find some time to look again more thoroughly in case there's anything I missed. Will do that today hopefully :-)

**Comment by rosieyohannan** [comment]
> This looks great and scales nicely on mobile. I noticed there is a bit of text/links in the upper right corner that might need to be moved?
> 
> Screen Shot 2020-08-17 at 9 58 30 AM

@teesloane I can't get it to look like that - is that what happens when you shrink your browser?

**Comment by teesloane** [comment]
This view happens on `circleci.com/docs`  but not on `/docs/2.0`

**Comment by teesloane** [comment]
I added a fix for the links not displaying correctly. The sidebar changes are looking good to me.

**Pull request closed without merging**
