### PR TITLE
Tabbed code blocks

### PR DESCRIPTION
**Pull request by felicianotech**
As discussed during yesterday's Docs meeting, this PR is a working example of Markdown code fences being "tabbed". The idea here is so that we can offer two versions of a config. The immediate scenario that comes to mind is showing a CircleCI v2.1/orbs config while still being able to show a CircleCI 2.0 config.

This PR contains two commits with two different styles. The first, a sleeker look while the second is a more traditional tab look.

The `HEAD` of this branch currently points to the latter style.

### Style 1

FireShot Capture 011 - Language Guide_ Ruby - CircleCI - localhost
FireShot Capture 012 - Language Guide_ Ruby - CircleCI - localhost

### Style 2

FireShot Capture 013 - Language Guide_ Ruby - CircleCI - localhost
FireShot Capture 014 - Language Guide_ Ruby - CircleCI - localhost

### CODE REVIEW

**Comment by iynere** [comment]
niiiiiice @felicianotech  i didn't know this was possible with Jekyll !

**Comment by teesloane** [comment]
Nice work @felicianotech ! I pulled your branch and tested it out and adding an additional tabs worked well. 

Screencast for those interested:
Kapture 2019-06-25 at 15 20 26

**Comment by iynere** [comment]
i dont have a preference between v1 or v2

**Comment by teesloane** [comment]
yeah, I'm easy  for whichever style. Probably leaning over to (that sit above the code block).

**Comment by michelle-luna** [comment]
I love this! Also showed to Katie and we both prefer the traditional tabs as well. can we merge and start using it? :D

**Comment by felicianotech** [comment]
Awesome.

We can't merge yet as this isn't ready. I need to finish implementing it, test it across browsers, and finally add into the Doc's docs how to use this. Then it will be ready to go. I'll follow up here when it's ready.

**Comment by michelle-luna** [comment]
Great! Let me know if there is any way I can help you out with testing/docs etc.

**Comment by felicianotech** [comment]
I got busy. This will be moved out of draft and ready by Monday.

**Comment by felicianotech** [comment]
Okay I've:

- rebased this PR on master
- tested this feature on Google Chrome 76, Chromium 76, and Firefox 68
- added it's info to the Doc's internal docs (WIDGETS.md)

**Comment by williswillz** [comment]
ok thanks

**Pull request merged**
