### PR TITLE
Adding howto for performing Maven releases

### PR DESCRIPTION
**Pull request by itzg**
Without this procedure I found myself needing to run the Maven release target locally on my development machine; however, that felt very dirty given the pristine, deterministic environment of a CircleCI build.

### CODE REVIEW

**Comment by felicianotech** [comment]
@smart-alek This will be our last new doc contribution for 1.0. Needs a copy-edit.

**Comment by itzg** [comment]
Thanks. FYI I now have access to the 2.0 beta, but haven't yet explored maven release workflows there.

**Comment by felicianotech** [comment]
@itzg Not a problem. We'll be starting a new set of docs for that so all in due time. :)

Can you do me a favor and allow us to edit your PR directly? This will help for the copy-edit and so that we can trigger a new build on CI. The setting should be near the bottom of the sidebar for this PR.

Thank you.

**Comment by itzg** [comment]
@felicianotech it looks like it was already enabled, but let me know if acts otherwise.

image

**Comment by keybits** [comment]
LGTM - thanks for the contribution 👍

**Pull request merged**
