### PR TITLE
Remove Docker image tag list from circleci-images

### LINKED ISSUE #5535: Incorrect listing for recent Postgres tags
# Locations

I'm working on adding a postgres container to my team's CircleCI workflow. In the documentation, there is a list of the most recent tags, here: https://circleci.com/docs/2.0/circleci-images/#postgresql

The list incorrectly says that the 9.x version of postgres is the latest set of tags. The actual most recent version is 13.x

# Details

I believe this is because of alphabetical sorting of the list of version numbers. The version numbers of postgres have now progressed to 13, but in string sort "9" is later than "1", so version 9.x comes up as most recent in this list even though 13.x is actually more recent. 

The source list from which this page is built can be found here: https://github.com/circleci/circleci-docs/blob/master/jekyll/_data/docker-image-tags.json#L10389 (which I think is itself created by this script: https://github.com/circleci/circleci-docs/blob/master/scripts/pull-docker-image-tags.sh)

This is the tag listing from Circle's DockerHub, ordered by most recently updated: https://hub.docker.com/r/circleci/postgres/tags?page=1&ordering=last_updated

This issue likely affects all software with version numbers starting with 10 or higher, though postgres is the one I observed.

### PR DESCRIPTION
**Pull request by tnir**
Signed-off-by: Takuya Noguchi <takninnovationresearch@gmail.com>

# Description
Removes Docker image tag list from circleci-images.

# Reasons
Closes #5535

### CODE REVIEW

**Comment by rosieyohannan** [comment]
@felicianotech could you take a look at this?

**Comment by tnir** [comment]
@felicianotech Why not merging this PR then?

**Review by thomasr8 — APPROVED** [review]

**Comment by tnir** [comment]
@thomasr8 @felicianotech What is left to get this merged?

**Comment by rosieyohannan** [comment]
Thanks @tnir, I think this must have been missed, Merging now! :-)

**Pull request merged**
