### PR TITLE
Update google-cloud-test-lab.md

### PR DESCRIPTION
**Pull request by doridori**
Clean up misleading doc steps that caused me to waste a bit of time setting up gcloud test lab with circle

### CODE REVIEW

**Comment by felicianotech** [comment]
Hi,

Thanks for your contribution. One issue I see with these changes so far is that these changes causes the doc to diverge with the GitHub project (linked near the top of the doc) that the doc is meant to be used with. The code samples are direct snippets from that project.

Was the sample repo (pulled from Google, with CircleCI specific changes) helpful to you? Did you have issues with it as well or did you not even use it?

**Comment by doridori** [comment]
Hi, 

I missed that actually - but being a typical man I generally don't bother with example projects as find it much easier to follow simple project-abstracted instructions! 

Personally Im not sure having an example project does anything but increase cognitive load. To use the test cloud you add the code in the wiki to your project that has runnable tests via the `./gradlew :app:assembleDebugTest` output apk. For me at least, reason the docs an applying it to my project is quicker than applying to an example project and working out what bits I have to change to apply to my own. Maybe thats just me though?

**Comment by mpp-doric** [comment]
Found myself going through this process again and see none of these changes have been pulled in. Would be good to have consistency across your documentation...

**Comment by doridori** [comment]
Found myself going through this process again and see none of these changes have been pulled in. Would be good to have consistency across your documentation...

**Comment by felicianotech** [comment]
We're going to be doing something different with example projects moving forward so these changes are good. Thanks again.

**Pull request merged**
