### PR TITLE
Add external MongoDB documentation

### PR DESCRIPTION
**Pull request by robinsturmeit**
# Description
This adds the documentation for using an external MongoDB instance

# Reasons
SERVER-1166

### CODE REVIEW

**Comment by annabaker** [comment]
is this 3.1 specific or meant to be live now?

**Comment by robinsturmeit** [comment]
> is this 3.1 specific or meant to be live now?

Ah, I need to target a different branch for 3.1, right? Which one was it, again?

**Comment by annabaker** [comment]
> > is this 3.1 specific or meant to be live now?
> 
> Ah, I need to target a different branch for 3.1, right? Which one was it, again?

no worries, server/3.1-preview. For future reference (I just added this a couple days ago after Nathan Smith suggested the naming conventions): https://github.com/circleci/circleci-docs#branch-nomenclature-for-subsequent-server-releases

**Review by MikeyYeahYeah — APPROVED** [review]

**Comment by MikeyYeahYeah** [comment]
Small Process Complaint:  There seems to a fair number of commits not related to externalizing MongoDB.  Not sure if it's possible but it would be nice of we could limit the scope of PR's to just the context of the change.

**Comment by annabaker** [comment]
Looks like there's a couple merge conflicts

> Small Process Complaint: There seems to a fair number of commits not related to externalizing MongoDB. Not sure if it's possible but it would be nice of we could limit the scope of PR's to just the context of the change.

@nsmith5 we talked about this before, wdyt?

**Comment by robinsturmeit** [comment]
Rebased the PR against the 3.1 branch, this should take care of your concerns :)

**Comment by annabaker** [comment]
> Rebased the PR against the 3.1 branch, this should take care of your concerns :)

thank you!

**Pull request merged**
