### PR TITLE
Add language guides

### PR DESCRIPTION
**Pull request by smart-alek**
@felicianotech Here's what I've done so far. Couple things:

1. I'm missing the Python doc and will get that one up here later today.
2. I can't automatically merge into `cci2-docs`, so I must need to rebase that into this branch?

### CODE REVIEW

**Comment by smart-alek** [comment]
OH, I see why the conflicts are happening. I remove "Integrations" and renamed "Language Guides" to "Quickstart Guides". No worries, then.

**Comment by felicianotech** [comment]
Rebasing first might resolve the conflicts, yes. Do you wanna try? Or do you want me to to redo the PR that way? Or you just wanna tackle the conflicts on their own?

**Comment by smart-alek** [comment]
@felicianotech ok just handled the conflicts, we should be good to go

**Comment by felicianotech** [comment]
Do you mind if I rebase your branch? You have a change we need to remove. To `jekyll/_ccie/index.html`.

**Comment by felicianotech** [comment]
I guess I can just add a commit too at this point.

**Comment by felicianotech** [comment]
@smart-alek took a look at this after the rebase. Once tests pass, merging.

**Pull request merged**
