### PR TITLE
docker-compose doesn't fit under deployment

### PR DESCRIPTION
**Pull request by zzak**
I put it under "containerization" instead

### CODE REVIEW

**Comment by keybits** [comment]
Agree. LGTM, but you may wish to get confirmation from @michelle-luna

**Comment by michelle-luna** [comment]
I think Nathan made the argument with me that this was only used in deployment so I moved it (maybe I misunderstood him)? I'm fine with this change if he agrees as well.

**Comment by ndintenfass** [comment]
The one I was most concerned with was https://circleci.com/docs/2.0/building-docker-images/ - which is, I think, in the right place now. No strong opinion on docker-compose.

**Comment by ndintenfass** [comment]
@zzak which sounds like you are go for :shipit:

**Pull request merged**
