### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by thomasr8**
Added content to document for change in Delete SSH Key endpoint

# Description
A brief description of the changes.

# Reasons
A link to a GitHub and/or JIRA issue (if applicable).
Otherwise, a brief sentence about why you made these changes.

### CODE REVIEW

**Comment by thomasr8** [comment]
This fixes #3143

**Comment by kimh** [comment]
Why don't we just merge https://github.com/circleci/circleci-docs/pull/3143? The two PRs look identical to me.

**Comment by yuya-takeyama** [comment]
Actually, this PR lacks a whitespace here:

circleci-docs 2019-02-21 10-57-17

**Comment by michelle-luna** [comment]
Sorry, for a period of time, we will have two docs, so I was requesting Thomas to add this change to the https://github.com/circleci/circleci-docs/blob/master/jekyll/_api/v1-reference.md file (but, I don't think I was clear about that)! Thank you, closing this one and merging the other one

**Pull request closed without merging**
