### PR TITLE
[BUG FIX] Node references in Python

### PR DESCRIPTION
**Pull request by nramabad**
# Description
Bug fix for Node.js references in Python tutorial

# Reasons
Typos can be confusing.

### CODE REVIEW

**Review by chantelle11 — APPROVED** [review]
Great catch! 💕💎👌

**Review by rsylvian — APPROVED** [review]

**Review by thomasr8 — COMMENTED** [review]
Just a comment here. You may wish to check with Ricardo from the CPE team about whether we are still supporting some of these python and heroku images. I know we just moved off legacy images, so "cimg" should not be part of any image.

**Comment by nramabad** [comment]
> Just a comment here. You may wish to check with Ricardo from the CPE team about whether we are still supporting some of these python and heroku images. I know we just moved off legacy images, so "cimg" should not be part of any image.

hey @thomasr8, thanks for the info. This PR is purely a bug fix given to make our current experiment less confusing. I'll definitely be sure, however, to discuss with Ricardo about removing the cimg reference.

**Comment by rsylvian** [comment]
> Just a comment here. You may wish to check with Ricardo from the CPE team about whether we are still supporting some of these python and heroku images. I know we just moved off legacy images, so "cimg" should not be part of any image.

@thomasr8 I am not sure I follow because this content is already using the latest images per the documentation:

> cimg/python: This image is designed to supercede the legacy CircleCI Python image, circleci/python

Orbs are still labeled `circleci/`: https://circleci.com/developer/orbs/orb/circleci/python

**Comment by thomasr8** [comment]
@nramabad and @rsylvian My mistake....sorry about that :(

**Review by thomasr8 — APPROVED** [review]

**Comment by thomasr8** [comment]
I just went ahead and approved. Sorry for the mistake.

**Comment by rsylvian** [comment]
No worries @thomasr8! Thanks for your help 🤗

**Pull request merged**
