### PR TITLE
Update docker-layer-caching.md

### PR DESCRIPTION
**Pull request by sebastian-lerner**
a really not great job of trying to describe how the new DLC implementation works.

@joshhsoj1902 what sort of things am i missing here that might be critical to call out?

for the docs team, we're replacing how DLC works "under the hood".  some details here: https://circleci.atlassian.net/wiki/spaces/ED/pages/6593282057/DLC+on+Machine+Provisioner+MPDLC

we want to make sure our docs are somewhat up to date if customers have questions on the new implementation.

### CODE REVIEW

**Comment by devinmarieb** [comment]
@sebastian-lerner I've gone through and made some styling edits, so let me know if you'd like to wait for Josh to weigh in on the actual info and if anything is missing, etc.

**Comment by sebastian-lerner** [comment]
still waiting on josh.  he's a bit busy with other stuff this week so this will likekly have to wait

**Comment by joshhsoj1902** [comment]
@sebastian-lerner I read this over and it looks good to me. The only other thing we could directly say is that the new DLC results in more consistency in build times vs the old model. but that is implied when we say that there are more cache hits.

I can't think of anything else that is worth mentioning

**Comment by sebastian-lerner** [comment]
@devinmarieb now that we have josh's blessing, any thoughts on how this is worded?

**Review by kbatuigas — APPROVED** [review]
Thank you 🙏

**Comment by sebastian-lerner** [comment]
@kbatuigas are you gonna merge? i dont think i have those permissions

**Comment by kbatuigas** [comment]
> @kbatuigas are you gonna merge? i dont think i have those permissions

Can do - thanks for the heads up!

**Comment by sebastian-lerner** [comment]
still waiting on josh.  he's a bit busy with other stuff this week so this
will likekly have to wait

**Pull request merged**
