### PR TITLE
Added a Minitest section to the test-metadata custom build guide.

### PR DESCRIPTION
**Pull request by djohnson**
This makes it clear how to configure Minitest to run in parallel.

### CODE REVIEW

**Comment by djohnson** [comment]
This should address issue #225

**Comment by eric-hu** [comment]
This looks good to me.  Thank you for the PR.

**Comment by eric-hu** [comment]
@djohnson Could you rebase your branch off of our current master?  I just noticed the merge conflict.

**Comment by felicianotech** [comment]
@djohnson Will you getting this branched rebased? Otherwise this PR will be closed soon.

**Comment by djohnson** [comment]
@felicianotech Just rebased this off master.

**Comment by eric-hu** [comment]
Thank you @djohnson !

**Pull request merged**
