### PR TITLE
Added September Partners

### PR DESCRIPTION
**Pull request by morganhennessy**
Removed CryptoMove

# Description
Added ConfigCat, Cloudsmith, Fairwinds, F0cal, Quali, Packtracker, Sumo Logic, and Neocortix

### CODE REVIEW

**Comment by rosieyohannan** [comment]
Are the orb references missing the first part in this change? the `something: ` bit at the front of each one? @thomasr8?

**Comment by teesloane** [comment]
Ack! I missed what Rosie said. It looks like the new additions need to be prefaced with a key like the rest of the items in thte list.

image

Can you make sure that gets in @morganhennessy ?

Thanks!

**Comment by morganhennessy** [comment]
Hi @michelle-luna @rosieyohannan @teesloane, I've gone in and added the missing piece. I also noticed a few in there that were missing it as well. Please let me know if this works and I'll watch to see if it's merged. Thanks!

**Comment by rosieyohannan** [comment]
@morganhennessy thank you! Looks Good 😎

**Pull request merged**
