### PR TITLE
Update Tutorials page to remove out of date sample projects

### PR DESCRIPTION
**Pull request by kbatuigas**
# Description
The Tutorials page contains a lot of out of date examples that are no longer supported. This PR is to start removing those examples from our docs site and direct readers to more up to date examples instead. 

We'll archive the existing list of language guides to the `/jekyll/archived/snippets/` folder in case we need it for future use.

As of 10/10 we've also decided that we will not be including a guide for users to create sample apps, and that work on [updating the side nav](https://github.com/circleci/circleci-docs/pull/5912#issuecomment-963735262) will be done in a separate PR.

# Reasons
We have a few new supported examples, and more will be created by the CPE team as we go.
https://circleci.atlassian.net/jira/software/projects/DOCSTEAM/boards/412?selectedIssue=DOCSTEAM-57

### CODE REVIEW

**Comment by kbatuigas** [comment]
Currently awaiting input re: sample app instructions based on private repo, and changes under the "Examples and Guides > Languages" left hand side nav section.

**Review by devinmarieb — APPROVED** [review]
looks good!

**Comment by devinmarieb** [comment]
@kbatuigas did we archive the old table anywhere? Might be worth saving the table to add it to some archive when we figure out the best place for that.

**Comment by kbatuigas** [comment]
@devinmarieb Yes! Although I only have it saved locally since I wasn't super sure if we had a best practice for archiving content like this. Thoughts? Should I create a new page that contains the old table?

**Comment by devinmarieb** [comment]
@kbatuigas From my understanding we don't want the content to be accessible to a user through a hidden link or anything, just stored somewhere, so I would maybe as Docs Disco what the best course of action is.

**Comment by kbatuigas** [comment]
Just to wrap up the conversation re: archiving - a `/jekyll/archived/snippets/` folder has been created.

**Pull request merged**
