### PR TITLE
Remove CIRCLE_PR_NUMBER

### PR DESCRIPTION
**Pull request by knil-sama**
No longer work, use to get the pr number ${CIRCLE_PULL_REQUEST##*/}

### CODE REVIEW

**Comment by smart-alek** [comment]
@knil-sama are you saying this environment variable isn't available? That is news to us!

Can you attach a sample job that shows the problem you're having?

**Comment by knil-sama** [comment]
Really ? For what I saw the problem is at least 2 years old

https://discuss.circleci.com/t/circle-pr-number-missing-from-environment-variables/3745/4
https://discuss.circleci.com/t/pull-request-number/972

**Comment by smart-alek** [comment]
@knil-sama Yikes, you're right!

Casual question: is your build forked?

**Comment by knil-sama** [comment]
Hi, so

1) 2.0
2) Build is not forked

**Comment by smart-alek** [comment]
Interesting. Originally, `CIRCLE_PR_NUMBER` was one of a few environment variables that only worked on forked build PRs. However! We recently discovered that it was available everywhere. That led to [this PR](https://github.com/circleci/circleci-docs/pull/2067).

I'm also a little confused because this PR is for 1.0 docs, but you said you're using 2.0, right?

**Comment by knil-sama** [comment]
Oh my mistake, indeed I should have referenced 2.0 documentation,
but I just created 2 PR (on for circle 1.0 and one for 2.0) and in both case I still didn't have any result.
[](https://github.com/knil-sama/lerustique/pulls)

**Comment by knil-sama** [comment]
My use case in circleci is something like this

```
version: 2

jobs:
  deploy:
     working_directory: ~/app
    docker:
       - image: custom_image
        environment:
          - CUSTOM_VARIABLE
    steps:
      name: Deploy scrip
      command: "./deploy.sh \"${CIRCLE_PR_NUMBER/}\""

 workflows:
   version: 2
   build-and-deploy:
     jobs:
       - other_jobs
       - deploy
```
And the output I get is empty

**Comment by smart-alek** [comment]
@knil-sama So, I'm going to close this PR for now. We had a JIRA ticket filed about something _very_ similar, so I'm going to reopen it and flag it to our engineers. Thanks for taking the initiative on filing this, but we want to really make sure we don't support it before removing it! :)

**Comment by knil-sama** [comment]
I am ok with the closing of this PR, but if the jira is public, can you add the link for this issue, I would to keep track of it.

**Comment by smart-alek** [comment]
Woof, unfortunately it's not public, but you have my **word** that I am pestering the responsible parties.

**Comment by OrkoHunter** [comment]
The environment variable `CIRCLE_PR_NUMBER` does not exist anymore. Would be good to remove from the docs.

**Pull request closed without merging**
