### PR TITLE
[SNC-140] added helper functions for contexts in CPM

### PR DESCRIPTION
**Pull request by gosuku**
# Description
A brief description of the changes.

New CPM helper functions are added for Contexts.

# Reasons
A link to a GitHub and/or JIRA issue (if applicable).
Otherwise, a brief sentence about why you made these changes.

https://circleci.atlassian.net/browse/SNC-140

# Content Checklist
Please follow our style when contributing to CircleCI docs. Our style guide is here: [https://circleci.com/docs/style/style-guide-overview](https://circleci.com/docs/style/style-guide-overview).

Please take a moment to check through the following items when submitting your PR (this is just a guide so will not be relevant for all PRs) 😸:

- [ ] Break up walls of text by adding paragraph breaks.
- [ ] Consider if the content could benefit from more structure, such as lists or tables, to make it easier to consume.
- [ ] Keep the title between 20 and 70 characters.
- [ ] Consider whether the content would benefit from more subsections (h2-h6 headings) to make it easier to consume.
- [ ] Check all headings h1-h6 are in sentence case (only first letter is capitalized).
- [ ] Is there a "Next steps" section at the end of the page giving the reader a clear path to what to read next?
- [ ] Include relevant backlinks to other CircleCI docs/pages.

### CODE REVIEW

**Review by davidmdm — CHANGES_REQUESTED** [review]
The docs look very good! There is only one issue. All of project based helpers take as arguments a string or array of strings or set of strings. 

So the signatures actually look like this:

```
contexts_*verb*_by_project_ids(projects: string | Array<string> | Set<string>, contexts: string | Array<string> | Set<string>)
```

**Comment by gosuku** [comment]
> 

Is this valid for Reserved by Branches as well?

**Review by davidmdm — APPROVED** [review]
Approving as to not be a blocker but `branches` should also be of type `string | Set<string> | Array<string>`

**Comment by davidmdm** [comment]
@rosieyohannan This PR is ready for Docs Team review!

**Comment by gosuku** [comment]
> Approving as to not be a blocker but `branches` should also be of type `string | Set<string> | Array<string>`

👍  added the recommended changes.

**Comment by rosieyohannan** [comment]
@gosuku I pushed some style updates, could you have a quick check and then I'll get this merged

**Comment by gosuku** [comment]
Thank you @rosieyohannan this looks great now.

**Review by rosieyohannan — APPROVED** [review]

**Pull request merged**
