### PR TITLE
Remove whitespace preceeding backticks

### PR DESCRIPTION
**Pull request by kimh**
Probably whitespace in front of code blocks is valid but our translation tool doesn't handle it, so we need to sanitize them. The problem with the translation tool is that the tool doesn't recognize it as code blocks and remove backticks from translated strings.

### CODE REVIEW

**Comment by michelle-luna** [comment]
Hi Kim, for the instances inside of steps, this may break the step numbering, so we should test this, will take a look later today, sorry for the delay

**Comment by kimh** [comment]
@michelle-luna Ping

**Comment by michelle-luna** [comment]
Have you tested this locally to see if the step numbering breaks? I think this breaks all the step numbering (all steps will be step 1 or restart to step one after this change).

**Comment by felicianotech** [comment]
It does break numbering.

**Comment by kimh** [comment]
@felicianotech where do we use step numbering?

**Comment by michelle-luna** [comment]
closing for now, re-open if you need it

**Pull request closed without merging**
