### PR TITLE
Fix markdown styles

### PR DESCRIPTION
**Pull request by teka23**
# Description
Based on https://github.com/circleci/circleci-docs/pull/5181

After introducing the markdownlinter, I have fixed the rule violations.

Preview: http://circleci-doc-preview.s3-website-us-east-1.amazonaws.com/te/fix-markdown-styles-preview/2.0/

# Reasons

After fixing these violations, there won't be any style rule violations in `jekyll/_cci2`.
This will help with Crowdin parsing issues.

### CODE REVIEW

**Comment by teesloane** [comment]
This is great! It will take me a long time to review this, but I will try to get it done soon.

**Comment by teesloane** [comment]
Just to confirm @teka23, I should review and approve/merge #5181 first, correct?

**Comment by teka23** [comment]
My plan is to merge #5181 to master after this PR. It is just based on this PR, so after merging this I can change the base branch to master.

**Comment by teesloane** [comment]
Hi @teka23 ! I am back from time off and hope to merge this this week. Do you mind fixing the merge conflicts and then I'll merge in? Thanks!

**Comment by teka23** [comment]
@teesloane I have fixed the merge conflicts.

**Review by teesloane — APPROVED** [review]

**Pull request merged**
