### PR TITLE
Slate API styling.

### PR DESCRIPTION
**Pull request by teesloane**
[Preview link.](https://60877-48750547-gh.circle-artifacts.com/0/circleci-docs/api/v2/index.html?ruby#circleci-api)

Based on [these design boards.](https://circleci.invisionapp.com/d/main#/console/20029593/421460044/preview)

### CODE REVIEW

**Comment by teesloane** [comment]
Unfortunately, Andrew (the designer who made the spec) doesn't seem to have a GitHub account - I'll see if I get that setup with him!

**Comment by asongci** [comment]
Testing Testing

**Comment by asongci** [comment]
@rosieyohannan Try this link: https://circleci.invisionapp.com/share/R7XHI7SS8UP

**Comment by asongci** [comment]
Some feedback from the design team: 
The search Icon and text is a little too small - Is there a possibility to increase the size? 
The Favicon looks a little outdated. Here are our updated favicons: 
[favicons-circle.zip](https://github.com/circleci/circleci-docs/files/4866061/favicons-circle.zip)
Can we also reduce the size of the CircleCI API logo?

-Thanks Tyler!

**Comment by teesloane** [comment]
Thank you @asongci ! Here is the update [link with the suggested changes](https://61480-48750547-gh.circle-artifacts.com/0/circleci-docs/api/v2/index.html).

**Comment by teesloane** [comment]
**Before**
Screen Shot 2020-07-06 at 1 51 56 PM


**After:** 
Screen Shot 2020-07-06 at 1 50 22 PM

**Comment by asongci** [comment]
@teesloane Hi Tyler! This is a little nitpicky, but do you think you can align the logo to the links on the top and in the sidebar as well? Similar to this: 
Screen Shot 2020-07-07 at 4 11 29 PM

**Comment by asongci** [comment]
I also got some feedback from the design team that the bar next to the links in the side-nav is hard to see. Could we add some more padding so it's not on the edge of the screen? 
image

**Comment by teesloane** [comment]
@asongci - latest requested changes are visible [here](https://61732-48750547-gh.circle-artifacts.com/0/circleci-docs/api/v2/index.html).

**Comment by asongci** [comment]
@teesloane Just saw the changes and it looks awesome! Thanks for making these changes.

**Comment by asongci** [comment]
@teesloane Hi Tyler! Apologies for bothering you again. When you visit the API page for the first time I noticed that the links "documentation" and "circleci.com" at the top are cut off. Is there a way to bump the middle section down a bit to show the links? This is also another small thing, but can we have the links open a new tab as well. 

When you click on the logo it goes to the Docs page. Can we change it so that it links to the very beginning of the API page?

Do you also have an update on the light background/code? Is it possible to implement that feature?

**Comment by teesloane** [comment]
No problem! I've merged in our changes thus far and they are now life - so I'll address your questions, and future ones will probably take place on another PR which I'll DM you in Slack (just a heads up :) )

- I will definitely address the docs icon links to the beginning of the page and the open in new tab functionality. I will also play with the light / dark background based on user-dark-mode preferences. It shouldn't be a problem. 

As for the heading being cut off - I'm not seeing that issue. Does this [link](https://circleci.com/docs/api/v2) have the same issue when you visit it?

**Comment by asongci** [comment]
@teesloane Awesome! Thank you for the update. The link you provided works and I see the links at the top. When you go to the circleci.com home page and click API under developers, I get that issue of the links being cut off.

**Comment by teesloane** [comment]
Ah gotcha - we'll need to issue a fix to outer, which is linked to a header anchor. Will look into it.

**Pull request merged**
