### PR TITLE
Enhancement/ccie docs

### LINKED ISSUE #607: CCIE Troubleshooting Category
The category page for this is showing non-CCIE docs. https://circleci.com/docs/enterprise/troubleshooting/

### PR DESCRIPTION
**Pull request by felicianotech**
This change is a long-time coming because CircleCI Enterprise (CCIE) Docs were kind of shoehorned into this repo. The basis for this PR is that CircleCI Docs is being divided into top-level "sections" (which Jekyll calls Collections) with the addition of 2.0 docs. Most of 1.0 docs will stay in its original collection, CCIE Docs are being moved to their own collection, and 2.0 docs will land soon as their own collection as well. This PR is part of the lead up to that.

---

## Changes

**All Enterprise docs moved into a collection** - basically this was `git mv jekyll/_docs/enterprise jekyll/_ccie`

**Updated category pages** - PR #603 introduced the new Jekyll layout for category pages, `jekyll/_layout/category-page.html`. This PR has all CCIE category pages use this new layout.

**New Index Page Jekyll Layout** - this PR introduces a Jekyll layout for easily creating index pages (basically list all categories/docs) for a collection, `jekyll_layouts/index-page.html`.

**CCIE Index Page Uses New Layout** - the old `jekyll/_docs/enterprise.md` file, which was used as an index for CCIE Docs, is now `jekyll/_ccie/index.md` and uses the new index page layout mentioned above.

**Sidebar Updated** - the sidebar was updated to make sure listing the CCIE nav still works.

**_config.yml** - Jekyll's config file was updated to create the CCIE Collection.

## Note

Until the new search system is implemented, or the current one patched, this PR will temporarily remove CCIE docs from the website's search results. This of course would not affect Google Search or any other external system. So we don't loss track of this potential issue, a separate GitHub Issue was opened, #609.

---

Fixes #607.

### CODE REVIEW

**Comment by felicianotech** [comment]
@keybits I added you as the main reviewer on here however, I would like you and @smart-alek to give this a look over. Once you guys are happy, we need to rope in someone from the CCIE team as well to make sure I didn't miss anything and that they are aware of the changes.

**Comment by ndintenfass** [comment]
Will any URLs change? We have some other work in progress that I want to coordinate with the SEs too.

**Comment by felicianotech** [comment]
@ndintenfass The PR does not change any URLs nor the physical look of any CCIE page. Unless there's an error, every single doc page will be exactly the same. This is just changing the underlying structure.

The exception is the Troubleshooting category page that is referenced, because that page is already broken. This PR fixes it.

**Comment by felicianotech** [comment]
G-Rey also somewhat reviewed this and provided feedback over Slack.

**Pull request merged**
