### PR TITLE
Improve VM service documentation

### PR DESCRIPTION
**Pull request by ryanwohara**
# Description
* k8s nodes don't need to communicate
* The SSH port is 54782
* CLI commands to create the security group

# Reasons
https://circleci.atlassian.net/browse/SERVER-1229

### CODE REVIEW

**Review by robinsturmeit — CHANGES_REQUESTED** [review]
I commented on the Jira ticket. Opening communication on ports 22 and 2376 between cluster and external VMs is necessary.

**Comment by ryanwohara** [comment]
The Jira comment doesn't seem accurate based on design docs: https://github.com/circleci/vm-service/blob/master/docs/design.md#task

**Comment by robinsturmeit** [comment]
> The Jira comment doesn't seem accurate based on design docs: https://github.com/circleci/vm-service/blob/master/docs/design.md#task

Let's keep the discussion within the ticket until resolved :)

**Comment by ryanwohara** [comment]
Robin is right - converting this to a draft

**Review by robinsturmeit — CHANGES_REQUESTED** [review]
Seems like you would still need to add the k8s cluster CIDR block to the rules in the CLI examples

**Comment by ryanwohara** [comment]
Super good callout ty

**Review by robinsturmeit — APPROVED** [review]
Thank you, this is great :)

**Pull request merged**
