### PR TITLE
The latest tag no longer exists its now current

### PR DESCRIPTION
**Pull request by owenjoliver**
# Description
This fixes the example as I ran into the issue when trying this just now

# Reasons
I ran into this issue just now and we have updated the latest tag to now be current so the build fails when using the example.

### CODE REVIEW

**Comment by devinmarieb** [comment]
Hey, @owenjoliver, something in the pipeline failed. I don't have the ability to try and rerun it. Could you check out the error and see what's wrong?
https://app.circleci.com/pipelines/github/circleci/circleci-docs/46306

**Comment by owenjoliver** [comment]
The error it is throwing is a re-auth error which is odd.

Could not find a usable config.yml, you need to reauthorize and approve the SAML-protected org.
Please sign out of CircleCI and log back in with your VCS before triggering a new pipeline.

**Comment by devinmarieb** [comment]
@owenjoliver It seems your token has become invalid, can you re-authorize? There's a support article about this issue here: https://support.circleci.com/hc/en-us/articles/360043002793-Troubleshooting-CircleCI-Access-After-Enabling-Github-SSO

**Comment by owenjoliver** [comment]
Thank you I have just done the re-auth so it should be ok again now

**Review by devinmarieb — APPROVED** [review]

**Pull request merged**
