### PR TITLE
[DD-824] Tooling and Javascript files removed

### PR DESCRIPTION
**Pull request by halie-kastl**
# Description
A large collection of Javascript code, unused assets, css, and packages are removed with this PR

please test locally before approving by running `yarn jekyll-dev` and navigating to the produced URL. This will mostly be unformatted HTML, but it will be functional. 

# Reasons
https://circleci.atlassian.net/browse/DD-824

# Content Checklist
Please follow our style when contributing to CircleCI docs. Our style guide is here: [https://circleci.com/docs/style/style-guide-overview](https://circleci.com/docs/style/style-guide-overview).

Please take a moment to check through the following items when submitting your PR (this is just a guide so will not be relevant for all PRs) 😸:

- [ ] Break up walls of text by adding paragraph breaks.
- [ ] Consider if the content could benefit from more structure, such as lists or tables, to make it easier to consume.
- [ ] Keep the title between 20 and 70 characters.
- [ ] Consider whether the content would benefit from more subsections (h2-h6 headings) to make it easier to consume.
- [ ] Check all headings h1-h6 are in sentence case (only first letter is capitalized).
- [ ] Is there a "Next steps" section at the end of the page giving the reader a clear path to what to read next?
- [ ] Include relevant backlinks to other CircleCI docs/pages.

### CODE REVIEW

**Comment by rsylvian** [comment]
Looks good so far. Here are a few things to address:

1. Seems like CI is going to be tweaked so it doesn't fail anymore.
2. Everything jest and cypress can be removed
3. Everything webpack can be cleaned up
4. Pretty sure `.datadog/` can also be removed (CI should not be using it anymore).
5. I don't think `jekyll/assets/fonts` are needed anymore
6. `.browserslist-stats.json` can be removed, the section about it in ReadMe as well
8. Based on everything removed, we should clean the `package.json` of all the commands we don't need anymore

**Review by rsylvian — COMMENTED** [review]
Fantastic! Looks really good 🎉

Like we said earlier, let's pair tomorrow to double check that everything is fine with `docs-platform` :)

**Review by chantelle11 — APPROVED** [review]
I ran this locally in docs platform and didn't find any issues 🤞 🌻

**Review by rsylvian — APPROVED** [review]
Works well! Paired with Halie on this and also double checked locally that everything is fine. Great job! 🎉

**Review by devinmarieb — APPROVED** [review]

**Pull request merged**
