### PR TITLE
Feat: Re-implement TOC highlighting

### PR DESCRIPTION
**Pull request by teesloane**
# Description

The original Highlight on scroll broke our main branch (see this [PR](https://github.com/circleci/circleci-docs/pull/5924)). This was because our tests were being imported into our production bundle due to glob imports. This issue has been fixed in [this pr](https://github.com/circleci/circleci-docs/pull/5966).

So, the changes in this PR are all the same as those introduced in the original at #5924 .

Preview visible [here](http://circleci-doc-preview.s3-website-us-east-1.amazonaws.com/tees-hl-toc-preview/2.0/hello-world/).

### CODE REVIEW

**Review by ccgeller — CHANGES_REQUESTED** [review]
This may just be an issue with how close the headings are to each other on the screen but
1. If I go to a # directly by entering it in the URL you can see that the wrong thing is highlighted
http://circleci-doc-preview.s3-website-us-east-1.amazonaws.com/tees-hl-toc-preview/2.0/migrating-from-github/#jobs-and-workflows
Screen Shot 2021-11-23 at 10 32 57 AM

2. If I click Job and Workflows the header `Concept` is highlighted
going_to_job_and_workflow

**Comment by teesloane** [comment]
> It seems like you should do a rebase and then it may clean up the PR a bit?

I wouldn't worry about it; @rsylvian rebased already and we can squash when we merge :)

**Comment by teesloane** [comment]
- [ ] 

> This may just be an issue with how close the headings are to each other on the screen but
> 
> 1. If I go to a # directly by entering it in the URL you can see that the wrong thing is highlighted
>    http://circleci-doc-preview.s3-website-us-east-1.amazonaws.com/tees-hl-toc-preview/2.0/migrating-from-github/#jobs-and-workflows
> 
> Screen Shot 2021-11-23 at 10 32 57 AM
> 
> 2. If I click Job and Workflows the header `Concept` is highlighted
>    going_to_job_and_workflow

This is an unfortunate side effect of the headlines being very close together. I'm not sure what we can do to avoid that.

**Comment by ccgeller** [comment]
I think that 1. is an issue with any url. If I type the following into URL the screen shot shows the wrong item highlighted.
http://circleci-doc-preview.s3-website-us-east-1.amazonaws.com/tees-hl-toc-preview/2.0/migrating-from-github/#configuration-comparison

Screen Shot 2021-11-23 at 2 14 02 PM

**Comment by ccgeller** [comment]
I think 2 is an issue with the header and having to use `scroll-margin-top` to account for it. So it is not actually scrolling to the perfect position.  
Screen Shot 2021-11-23 at 2 16 47 PM

**Comment by ccgeller** [comment]
> > It seems like you should do a rebase and then it may clean up the PR a bit?
> 
> I wouldn't worry about it; @rsylvian rebased already and we can squash when we merge :)

Okay dokie! Thank you! I saw changes that were from the 'remove globing to prevent tests' PR and was unsure why it was showing up as new changes since that PR was merged.

**Comment by rsylvian** [comment]
I don't necessarily disagree with @ccgeller but let's merge this and create a follow-up ticket if we want to tweak this. I understand that the highlight might not be perfect when two headings are next to each other (like Concept & Jobs and Workflows) but I still think there is a bug when you visit that page the first time: http://circleci-doc-preview.s3-website-us-east-1.amazonaws.com/tees-hl-toc-preview/2.0/migrating-from-github/#jobs-and-workflows 

and this is the highlighting we get:

Screen Shot 2021-11-23 at 11 33 29 AM

**Review by rsylvian — APPROVED** [review]
Approving because it's the same thing as the previous PR. Probably can tweak some of the behavior in a future ticket though 👍

**Comment by ccgeller** [comment]
Okay here is an example of it working
scrolling_working

**Review by ccgeller — APPROVED** [review]
wooo! 🦾👍🤯

**Comment by Vendetta26** [comment]
tees/highlight-toc-scroll-CIRCLE-38942

**Pull request merged**
