### PR TITLE
Add additional documentation for LOS

### PR DESCRIPTION
**Pull request by robinsturmeit**
# Description
Adds additional documentation on how to use the Local Observability
Stack and its dashboards.

# Reasons
SERVER-412

### CODE REVIEW

**Comment by robinsturmeit** [comment]
> @robinsturmeit I imagine @annabaker might be better suited to review the content of this review, but can you remove the `package-lock.json` changes (if deps need to change it should happen in another PR). Thanks!

It was just the lock file, but sure, removed it from the PR

**Comment by nathanfishcircleci** [comment]
So Grafana includes data you would find in telegraf as well as other interesting data like CPU, etc? Telegraf is just statsd data from the services? Anyway we can make that more explicit in the documentation?

**Comment by robinsturmeit** [comment]
> So Grafana includes data you would find in telegraf as well as other interesting data like CPU, etc? Telegraf is just statsd data from the services? Anyway we can make that more explicit in the documentation?

Better now?

**Review by nathanfishcircleci — APPROVED** [review]
Looks good.

**Comment by nathanfishcircleci** [comment]
@annabaker i think once you approve this can be published.

**Comment by annabaker** [comment]
Closing -- moved this work over to #5362 (@robinsturmeit thank you so much! If you append '-preview' to the branch name, it will generate the preview site which helps me ensure there are no formatting errors prior to merging, etc.)

**Pull request closed without merging**
