### PR TITLE
ja: Make URLs clickable

### PR DESCRIPTION
**Pull request by tnir**
Signed-off-by: Takuya Noguchi <takninnovationresearch@gmail.com>

# Description
Make URLs clickable by using half-width spaces around them.

# Reasons
They should be clickable in some editors (e.g. VSCode) while they are not on https://circleci.com/docs/ja/2.0/language-ruby/.

### CODE REVIEW

**Comment by devinmarieb** [comment]
@circleci/translations Is this something that can be merged without causing trouble with Crowdin?

**Comment by tnir** [comment]
I hope Crowdin for translations is open for (non- `@cirleci`) contributors 😁

**Comment by devinmarieb** [comment]
@tnir Typically we won't accept contributions to our _ja pages as our current translation set up does not work well for OSS contributions. Ultimately contributions get over-written by our automated translation service. We are working on making this system better as we expand our team in Japan. But these things take time 😄

**Comment by Mayuko-Sa** [comment]
@tnir Thank you for your contribution.

**Review by Mayuko-Sa — APPROVED** [review]

**Comment by tnir** [comment]
Thanks!

**Pull request merged**
