### PR TITLE
add faq item about whitelisting of IPs

### PR DESCRIPTION
**Pull request by bear**
an easter present for @levlaz

### CODE REVIEW

**Comment by felicianotech** [comment]
When do you want this published?

If soon, this needs to be in the frontend repo. If it can wait a few days, this needs to be against the 'phase-1' branch. If you're going for the latter, I can move it over for you.

**Comment by bear** [comment]
no urgency at all @felicianotech -- I was asking the question in support and discovered it was not in the FAQ so added it.

**Comment by felicianotech** [comment]
Sorry about that. When I remade master this PR got autoclosed. I pulled in your changes here: https://github.com/circleci/circleci-docs/commit/8352f70a9065e33e7f2e5e4c50b096ed3fa39b4a

**Comment by bear** [comment]
no worries - thanks!

**Pull request closed without merging**
