### PR TITLE
CCIE External Database Documentation

### PR DESCRIPTION
**Pull request by MikeyYeahYeah**

### CODE REVIEW

**Comment by MikeyYeahYeah** [comment]
Quick note about the curl command.  I don't have the script available publicly yet.  Would need a place to put it if we decide to go that route.

**Comment by MikeyYeahYeah** [comment]
Just realized that I left out a section on restoring the databases.  Should this be included in the guide?

**Comment by smart-alek** [comment]
@MikeyYeahYeah if you're thinking of it as something you "left out", then I'd say it should be added. :)

**Comment by felicianotech** [comment]
Is this script something that is used itself and should be maintained? Then I'd say put it in its own repo. If not, then probably a GitHub Gist on the CircleCI org that we can then embed into the doc.

If the script is only a few lines though, then inside the doc itself is fine.

**Comment by felicianotech** [comment]
Added some formatting edits and properly capitalized PostgreSQL.

**Comment by ndintenfass** [comment]
Looks like lots of old commits got out here. Can we clean that up?

**Comment by MikeyYeahYeah** [comment]
My git-fu is awful.  I am sorry about that :-(

On Wed, Mar 22, 2017 at 8:18 PM, Nathan Dintenfass <notifications@github.com

**Comment by MikeyYeahYeah** [comment]
Moved to https://github.com/circleci/circleci-docs/pull/920

**Pull request closed without merging**
