### PR TITLE
Update Docs footer in line with website

### PR DESCRIPTION
**Pull request by rosieyohannan**
https://circleci.atlassian.net/browse/CIRCLE-15711?atlOrigin=eyJpIjoiZTBlNjljMmMzNWFmNDdjYWFkZjc0YmEyOTZlNjIyNmIiLCJwIjoiaiJ9

### CODE REVIEW

**Comment by rosieyohannan** [comment]
For reference website footer: https://github.com/circleci/circleci.com/blob/master/src/_includes/footer.html

**Comment by michelle-luna** [comment]
Is this ready, or still a WIP until Leslie reviews it?

**Comment by teesloane** [comment]
Just a heads up — I'm trying to fix/implement the language-selector currently 😅 so... wip?

**Comment by teesloane** [comment]
Here's my crack at adding the switcher to the footer:

Kapture 2019-09-11 at 11 56 10

**Comment by teesloane** [comment]
I'm actually running into issues with this on mobile (picker defaults to open) so I'm trying to debug that. If you want to merge now, I can revert my changes and try something later.

**Comment by rosieyohannan** [comment]
@teesloane oh weird is the language switcher taking you to the web homepage rather than the translated docs? I guess that's because I copied the code over from the website repo, so we can probably change the redirect address to docs and it will "Just Work"? (hopeful?!)

**Comment by rosieyohannan** [comment]
Thanks for sorting this out btw @teesloane 👏🏻

**Comment by teesloane** [comment]
@rosieyohannan — yep, @michelle-luna requested having it go to the .jp home page. Right now it's broken on mobile though, defaulting to being open.

**Comment by rosieyohannan** [comment]
I've just sent a link to Leslie to see if she would like to review before we merge these changes :-)

**Comment by lelau** [comment]
@rosieyohannan - we're also working on an updated selector - https://circleci.atlassian.net/browse/MKTG-1301

**Comment by lelau** [comment]
@teesloane - How do I see a preview of the updated docs? I tried to build locally with "rake serve", but that didn't work.

**Comment by teesloane** [comment]
@lelau you'll need to follow these steps: [README-local-development](https://github.com/circleci/circleci-docs/blob/master/README-local-development.md). I'd recommend using docker-compose.

**Comment by lelau** [comment]
@rosieyohannan - I was able to get my local build to work. And, I can see the language selector. However, it wasn't clickable.

**Comment by teesloane** [comment]
I will try and take another look at this on monday; hopefully it's a case of the javascript not registering in your build and it's working otherwise. In the meantime, can you try opening the inspector and checking for any errors when the page loads / you click the selector?

**Comment by teesloane** [comment]
Two part update:

1) Changes from #3727 have been moved into this PR. The content is similar enough that this should be one pr and will save the headache of multiple reviews + merge conflicts


2) The JS should be working now @lelau. I suspect that you need to regenerate the Javascript files with webpack, as docker-compose doesn't seem to do this.  I'm actually  just developing directly in jekyll right now since docker seems to be finicky (jekyll isn't much better). Right now I run these commands in the `/jekyll` subdirectory

trash _site; npm run webpack-prod; jekyll serve -Iw

which

1) `trash _site`: clears the _site cache (I use the `[trash](https://www.npmjs.com/package/trash)` utility, but you can just navigate to the folder and delete it.
2) `npm run webpack-prod` : should run the compilation of js changes
3) `jekyll serve -Iw` should serve up the docs to test.

Let me know if this isn't working and we'll get to the bottom of it!

In which case, this should show you the working picker.

**Pull request merged**
