### PR TITLE
show where to see IP ranges usage

### PR DESCRIPTION
**Pull request by sebastian-lerner**
# Description
A brief description of the changes.

# Reasons
A link to a GitHub and/or JIRA issue (if applicable).
Otherwise, a brief sentence about why you made these changes.

### CODE REVIEW

**Comment by devinmarieb** [comment]
@sebastian-lerner There is no included image of the UI here -- instead there is instruction to add an image (**picture goes here**). We can't merge this without an appropriate photo of the UI if that's necessary.

**Review by devinmarieb — CHANGES_REQUESTED** [review]
This needs an image if we're specifically referencing being able to see something in the UI. The assumption of including an image of the UI in the docs is that finding this information in a specific location in the UI is unlikely to change anytime soon. Please make sure the image has an appropriate file name for SEO purposes and has been optimized for the web.

**Comment by sebastian-lerner** [comment]
@devinmarieb sorry i'm working with rosie to get the picture in there

**Comment by devinmarieb** [comment]
@sebastian-lerner perfect thanks!

**Comment by rosieyohannan** [comment]
@sebastian-lerner I'm going to close this PR and open a new one :-D

**Pull request closed without merging**
