### PR TITLE
Update CODEOWNERS

### PR DESCRIPTION
**Pull request by rsylvian**
# Description
- Remove `@circleci/translations` from CODEOWNERS file

# Reasons
The `@circleci/translations` team doesn't exist anymore and is blocking some PRs to move forward.

# Content Checklist
Please follow our style when contributing to CircleCI docs. Our style guide is here: [https://circleci.com/docs/style/style-guide-overview](https://circleci.com/docs/style/style-guide-overview).

Please take a moment to check through the following items when submitting your PR (this is just a guide so will not be relevant for all PRs) 😸:

- [ ] Break up walls of text by adding paragraph breaks.
- [ ] Consider if the content could benefit from more structure, such as lists or tables, to make it easier to consume.
- [ ] Keep the title between 20 and 70 characters.
- [ ] Consider whether the content would benefit from more subsections (h2-h6 headings) to make it easier to consume.
- [ ] Check all headings h1-h6 are in sentence case (only first letter is capitalized).
- [ ] Is there a "Next steps" section at the end of the page giving the reader a clear path to what to read next?
- [ ] Include relevant backlinks to other CircleCI docs/pages.

### CODE REVIEW

**Review by devinmarieb — APPROVED** [review]

**Comment by cci-jassad** [comment]
should get a review from @circleci/security-operations ?

**Review by bear — CHANGES_REQUESTED** [review]
Can you update the team reference for docs-disco with CPEng - I believe that is where that team has moved under

**Comment by devinmarieb** [comment]
@bear Romain has stepped away for a bit, but Docs Disco has been dissolved, so the team has not moved anywhere new.

**Comment by bear** [comment]
> @bear Romain has stepped away for a bit, but Docs Disco has been dissolved, so the team has not moved anywhere new.

ah - then can we strike that team from the file

**Comment by devinmarieb** [comment]
@bear The DD team is being removed in this PR here
https://github.com/circleci/circleci-docs/pull/7674/commits/31da616728ca2e62a4e4b69ceb8eab2d0603e615

**Comment by bear** [comment]
> @bear The DD team is being removed in this PR here [31da616](https://github.com/circleci/circleci-docs/commit/31da616728ca2e62a4e4b69ceb8eab2d0603e615)

can we get someone to approve that PR then and then I'll merge these both

**Comment by devinmarieb** [comment]
@bear Yeah I think Romain is waiting because the CPENG team doesn't seem to actually exist yet...He will be back later.

**Comment by bear** [comment]
> @bear Yeah I think Romain is waiting because the CPENG team doesn't seem to actually exist yet...He will be back later.

ok, yea - we should have caught up with that task and they are fully added. I'll wait for Romain to return and sync with them

**Comment by rsylvian** [comment]
@bear I approved https://github.com/circleci/circleci-docs/pull/7674 :)

**Review by bear — APPROVED** [review]

**Pull request merged**
