### PR TITLE
Clarify usage of machine image key for Server

### PR DESCRIPTION
**Pull request by heug**
# Description
Add additional clarification that it is possible to use other image keys for Server installs

# Reasons
Customer wasn't interpreting this in the right way, so wanted to clarify to avoid confusion

### CODE REVIEW

**Comment by rosieyohannan** [comment]
Hey @heug I'm not sure this is true? Happy to be wrong though of course! Here's a slack convo from when I tried to clear this up a while back: https://circleci.slack.com/archives/CAT9Q7TGW/p1574767654216200 ... Maybe what we need to do is point out that the actual default image that gets used here is changable by the sys admin for the server install? But I didn't think it was the actual image key that would be changed. Let me know what you think :-)

**Comment by heug** [comment]
Gave it another go at clarification, thank you for linking me to that conversation!

**Comment by rosieyohannan** [comment]
@heug Do you have examples of the other image keys that can be used? I was under the impression this was not possible.

**Comment by heug** [comment]
`ubuntu-1604:201903-01` looked to be working, and a customer reported that they are able to use images from a private Docker registry

**Comment by appplemac** [comment]
I believe it’s only possible to use Machine images with Machine executor. Using Docker images won’t work in the `image` key for the Machine executor.

**Comment by rosieyohannan** [comment]
Closing this for now, but we can move the discussion to Slack 😀

**Pull request closed without merging**
