### PR TITLE
Add basic Clojure language guide.

### PR DESCRIPTION
**Pull request by technomancy**
This one uses this sample project I just pushed.

### CODE REVIEW

**Comment by technomancy** [comment]
Not sure what's going on with the syntax here:

    Liquid Warning: Liquid syntax error (line 103): Expected end_of_string but found string in "{{ checksum "project.clj" }}" in /home/ubuntu/circleci-docs/jekyll/_cci2/language-clojure.md

I tried to follow the example in the Python guide.

**Comment by felicianotech** [comment]
@technomancy You're missing the Liquid raw tags before and after the YAML block.

**Comment by technomancy** [comment]
No, that's perfect; thanks @felicianotech!

Any thoughts on the content before we merge?

**Comment by felicianotech** [comment]
I haven't read through too many of the other ones but this seems fine to me. LGTM.

**Comment by zzak** [comment]
LGTM

**Comment by technomancy** [comment]
Thanks folks.

**Pull request merged**
