### PR TITLE
Build-tools 23.0.2 isn't actually installed

### PR DESCRIPTION
**Pull request by ryanarlan0622**
(venv-2.7.9)ubuntu@box536:/usr/local/android-sdk-linux/build-tools$ ls -l
total 0
drwxr-xr-x 1 ubuntu ubuntu 394 Mar 22 02:56 20.0.0
drwxr-xr-x 1 ubuntu ubuntu 548 Mar 22 02:56 21.1.2
drwxr-xr-x 1 ubuntu ubuntu 572 Mar 22 02:56 22.0.1
drwxr-xr-x 1 ubuntu ubuntu 470 Mar 22 02:56 23.0.1

### CODE REVIEW

**Comment by kimh** [comment]
Thanks! I noticed this bug and now working on fixing. The change LGTM.

**Comment by felicianotech** [comment]
As far as I knew, these weren't installed. It's what available to be installed via Android Tools.

Also, I don't think this file is used anymore due to this PR? https://github.com/circleci/circleci-docs/pull/63

**Comment by ryanarlan0622** [comment]
According to our documentation (and even the new version) it says that that version of build-tools was "pre-installed" which as you can see it wasn't.  This was causing confusion (https://discuss.circleci.com/t/installing-android-build-tools-23-0-2/924/8) for multiple customers, and we were getting tickets from customers not expecting to have to install it.  I don't know if the new format fixes this, or if @kimh is just going to add it to the image so it is preinstalled.

**Comment by kimh** [comment]
Here is what's happening: we specify `build-tools-23.02` to be installed and the image making build succeeded but `android` command actually failed to install the build tool. While we are fixing this, I agree with @ryanarlan0622 to remove it from our doc. The doc has a new structure for build image because of #63 so this PR is not relevant anymore.

I'll take care of this in https://github.com/circleci/circleci-docs/pull/71

**Comment by ryanarlan0622** [comment]
Awesome, thanks @kimh I'll close this out

**Pull request closed without merging**
