### PR TITLE
Update collect-test-data.md

### PR DESCRIPTION
**Pull request by iynere**
add info on how to have Jest properly allocate CPU resources to avoid degraded performance in CI environments

### CODE REVIEW

**Comment by felicianotech** [comment]
Wasn't the fix to switch from `--runInBand` to `--maxWorkers=2`? Or am I reading that Issue thread wrong?

**Comment by iynere** [comment]
i believe you may be misreading it....

> there's a bug in Circle builds where running jest ***without*** `--runInBand` attempts to use the number of CPUs of the machine rather than the VM (which would make things worse). The `--runInBand` flag ***"fixes"*** this by forcing it to one worker

that said—

> you should be able to use `-w` for up to the number of CPUs given to the Circle VM

so, if a customer knows they have `N` CPUs, then they can use `--maxWorkers=N`

**Comment by felicianotech** [comment]
Yeah that's what they said but then look at the PR they did to fix the issue: https://github.com/facebook/react/pull/11983/files

I think the problem was that `--runInBand` isn't seeing the right number of vCPUs which is why setting it explicitly was done.

**Comment by iynere** [comment]
`--runInBand` doesn't look for number of vCPUs, it forces Jest to use a single worker

**Comment by iynere** [comment]
the PR used `--maxWorkers=2` because in that particular case, they knew that their CircleCI build had 2 vCPUs (which is not always the case)

**Comment by felicianotech** [comment]
I was under the impression that two vCPUs were the minimum offering by apparently (https://circleci.com/docs/2.0/configuration-reference/#resource_class) it's not.

Your method looks best then. :+1:

**Pull request merged**
