### PR TITLE
Describe how to use BATS

### PR DESCRIPTION
**Pull request by Peter-Darton-i2**
# Description
Adds a section that describes how to use BATS (the unit-test framework recommended by CircleCI for testing scripts in orbs).

# Reasons
This is non-trivial because CircleCI can't ingest the format output by BATS natively and the CircleCI "bats" orb doesn't do it either (see bats orb [issue 4](https://github.com/CircleCI-Public/BATS-orb/issues/4)), leaving users without a good example/easy path to follow without this documentation.
...and this is important because BATS is highlighted as "the" way of testing scripts in orbs, and orb development is core to CircleCI.

# Content Checklist

- [x] Break up walls of text by adding paragraph breaks.
- [x] Consider if the content could benefit from more structure, such as lists or tables, to make it easier to consume.
- [x] Keep the title between 20 and 70 characters.
- [x] Consider whether the content would benefit from more subsections (h2-h6 headings) to make it easier to consume.
- [x] Check all headings h1-h6 are in sentence case (only first letter is capitalized).
- [x] Is there a "Next steps" section at the end of the page giving the reader a clear path to what to read next?
- [x] Include relevant backlinks to other CircleCI docs/pages.

### CODE REVIEW

**Comment by devinmarieb** [comment]
@Peter-Darton-i2 Thank you for this! I will double check the examples with the Orbs team 🙌

**Comment by Peter-Darton-i2** [comment]
This is one of those situations where the documentation is "a bit ugly" because the UX is (currently) "a bit ugly" - we can (and should) document that to make the ugliness as painless as possible...

... but this should also be a wake-up call to get the functionality "de-uglified" so that the resulting documentation can be updated to say "Yes, this is (now) easy".
(and, if the functionality is changed to make the UX nice & easy then I'd be happy to make another PR simplifying the docs 😁)

**Comment by devinmarieb** [comment]
Hey @Peter-Darton-i2, sorry for the wait. The team is actually working on updating the orb to support this. I was not given a timeframe, but it is being worked on.

**Comment by Peter-Darton-i2** [comment]
No worries; updating the orb to make it so easy to use that it barely needs documenting at all is, IMO, a _much_ better option than having documentation explain a gnarly workaround 😁

I'll keep an eye on orb progress (via support) and, if/when that comes to fruition, I'll update this PR (or close it, if the orb team update the docs as part of that work).

**Comment by Peter-Darton-i2** [comment]
@devinmarieb FYI [circleci/bats@1.1.0](https://circleci.com/developer/orbs/orb/circleci/bats?version=1.1.0) has been released.
I've updated my PR to take advantage of it (it's now _really_ simple 👍).

WDYT?

**Comment by devinmarieb** [comment]
@Peter-Darton-i2 Nice thank you for staying on top of this! I just made some minor changes to keep with the style we use in docs wording 👍

**Review by devinmarieb — APPROVED** [review]

**Pull request merged**
