### PR TITLE
Grouping dependencies, database, and test together

### PR DESCRIPTION
**Pull request by kimh**
@technomancy suggested to group dependencies, database, and test sections into the same category because they are just bunch of run steps.

Also, cache_save -> save_cache

### CODE REVIEW

**Comment by kimh** [comment]
Note to self: make sure to update "database" section for PG thing

**Comment by technomancy** [comment]
This is great; thanks. Minor suggestion: "Database is not created automatically in 2.0." should probably be "The database is not ...".

Also I'm not 100% sure about this, but it seems that adding `save_cache` without ever restoring it doesn't benefit you, right?

Other than that it looks great.

**Comment by kimh** [comment]
> Also I'm not 100% sure about this, but it seems that adding save_cache without ever restoring it doesn't benefit you, right?

This is correct but the purpose of this article is giving users a simple 1-to-1 mapping between 1.0 and 2.0 config. There is no config equivalent to `restore_cache` in 2.0. I think we should cover `restore_cache` in a different page dedicated to caching.

I'll add a note that users have to run `restore_cache` manually in 2.0 and link to more details.

**Comment by kimh** [comment]
Addressed feedbacks. Merging.

**Pull request merged**
