### PR TITLE
Add notes about jobs being triggered using the API

### PR DESCRIPTION
**Pull request by sryabkov**
This commit/PR contains specific language addressing issues raised in #2383

### CODE REVIEW

**Comment by sryabkov** [comment]
@smart-alek FYI ^^^

**Comment by smart-alek** [comment]
@sryabkov thanks for submitting this. Your last note in #2383 did indeed help clear some stuff up.

I've been chatting with one of our product managers @KunalJain about the original problem you're trying to solve. Our concern is that we'd rather not document confusing behavior for a workaround. The _best_ solution would be to have first-class support for triggering a workflow.

Can you talk to us a little bit about what you're trying to accomplish by triggering a particular job in a workflow — rather than the workflow itself?

**Comment by smart-alek** [comment]
@sryabkov thanks for taking (even more) time to write this up. Consider me convinced! I'll continue chatting with @KunalJain about a more robust solution for the long-term.

But! In the meantime, let's get this merged; two additional notes are not going to hurt the integrity of this document. ;)

**Comment by sryabkov** [comment]
@smart-alek 👍 Thank you. Let me know if you have any other questions. 

By the way, what's the best way to communicate a suggestion/enhancement request? I have some suggestions on improving the workflows, which crystallized in my head as the result of our discussion.

**Comment by smart-alek** [comment]
@sryabkov absolutely! I've got an incoming PR that cleans up this document a bit more, which I'll link to in the issue you initially created. You can take a look at that to make sure my "improvements" haven't sullied your original intents. 😬 

As for communicating suggestions/enhancements, we've got a public [Ideas board](https://circleci.com/ideas/) where customers can submit and vote on their favorite suggestions.

Thanks again for all the communication!

**Comment by sryabkov** [comment]
@smart-alek 

If you tag me on your upcoming PR, I'll be happy to review it. I found some more confusing and inaccurate things on that page.

I posted the comment below to the `CCI-I-192 Trigger workflows via CircleCI REST API` in the [ideas board](https://circleci.com/ideas/). I didn't find a way to get a direct link (if there is none, it is an oversight, in my opinion).

> At the moment, even if it is not possible to trigger the entire workflow, it is possible to trigger a particular job that is referenced in the workflow. It is possible to re-implement the workflow (or implement a completely different one) by making the job call other jobs using the API. The mechanics are described in the documentation (https://circleci.com/docs/2.0/api-job-trigger/). 
> However, when a job is triggered using the API, context environment variables are not available to the job, even if the job references the context in the workflow definition (which sounds like a bug, if not an implementation one than definitely a requirements/design/user experience one). As a workaround, it is possible to define environment variables on the project level, but that defeats the whole point of context environment variables. I'd like to flag this issue here to make sure that it gets addressed as part of the effort to enable triggering workflows using the API.

**Comment by smart-alek** [comment]
@sryabkov whoops, I actually already made the PR (#2395), but if you found other stuff that needs changing, let's get it fixed in another issue. Thanks for all the time you've spent helping us get a better grip on this. :)

**Comment by sryabkov** [comment]
@smart-alek No problem, and sure, I am glad to help. 

In #2395, you corrected the definition of `CIRCLE_API_TOKEN` at the top of the page, in the [Overview](https://circleci.com/docs/2.0/api-job-trigger/#overview) and correctly stated that it is a Personal Access Token, not a Project-level environment variable. The problem is `CIRCLE_API_TOKEN` is also referenced in the second part of the page, in the [Conditionally Running Jobs With the API](https://circleci.com/docs/2.0/api-job-trigger/#conditionally-running-jobs-with-the-api) section, but over there it means something different. In _that_ section, `CIRCLE_API_TOKEN` _is_ a Project-level environment variable. 

I just created #2407 to address another small issue on that page.

**Comment by smart-alek** [comment]
Ah, yep — fair enough! These are the kinds of inconsistencies I love fixing, so the more 👀, the better! I'll make an issue to straighten out the overloaded variable name. 👍

**Pull request merged**
