### PR TITLE
Add `orb-author-intro` link to te docs

### PR DESCRIPTION
**Pull request by suryasr007**
# Description
The guide should assume that the developer has read both the [Introduction to an orb](https://circleci.com/docs/2.0/orb-intro) and [Introduction to authoring an orb](https://circleci.com/docs/2.0/orb-author-intro.)

# Reasons
The developer needs to have introductory knowledge on developing an orb.

### CODE REVIEW

**Comment by suryasr007** [comment]
@teesloane / @KyleTryon  Review ^^

**Review by rosieyohannan — APPROVED** [review]

**Comment by rosieyohannan** [comment]
@suryasr007 sorry for the delay here but could you pull the latest master into your branch to get it to pass? then we can merge :-)

**Comment by suryasr007** [comment]
@rosieyohannan done.

**Review by thomasr8 — APPROVED** [review]

**Comment by rosieyohannan** [comment]
Thanks so much for your contribution @suryasr007! 🎉

**Pull request merged**
