### PR TITLE
Replaced privacy policy link from the global footer

### PR DESCRIPTION
**Pull request by yuki-sakamoto-san**
# Description
I replaced the link for the privacy policy from the old to the new (https://circleci.com/legal/privacy/)

# Reasons
We replaced these links across the Outer and Marketo because the previous URL was redirecting to our legal portal which is privacy.circleci.com. 

We made this decision a while ago that, we'd only want folks who want to take an action against their personal data to be landed on privacy.circleci.com - everyone else should land https://circleci.com/legal/privacy/

# Content Checklist
Please follow our style when contributing to CircleCI docs. Our style guide is here: [https://circleci.com/docs/style/style-guide-overview](https://circleci.com/docs/style/style-guide-overview).

Please take a moment to check through the following items when submitting your PR (this is just a guide so will not be relevant for all PRs) 😸:

- [ ] Break up walls of text by adding paragraph breaks.
- [ ] Consider if the content could benefit from more structure, such as lists or tables, to make it easier to consume.
- [ ] Keep the title between 20 and 70 characters.
- [ ] Consider whether the content would benefit from more subsections (h2-h6 headings) to make it easier to consume.
- [ ] Check all headings h1-h6 are in sentence case (only first letter is capitalized).
- [ ] Is there a "Next steps" section at the end of the page giving the reader a clear path to what to read next?
- [ ] Include relevant backlinks to other CircleCI docs/pages.

### CODE REVIEW

**Review by devinmarieb — APPROVED** [review]

**Comment by devinmarieb** [comment]
@circleci/docs-disco Can you also approve/verify this?

**Comment by devinmarieb** [comment]
@circleci/docs-disco Just an FYI in case anything else needs changing regarding this

**Review by Mayuko-Sa — APPROVED** [review]

**Comment by j2em6h** [comment]
Looks like this might actually be coming from https://github.com/circleci/docs-devhub-ui-lib/blob/main/src/internal/translations/footer.json

**Comment by j2em6h** [comment]
> Ah looks like I don't have write access to that.

I don't either.

**Comment by chantelle11** [comment]
It seems like this needs to be addressed in another PR. The current code highlighted is deprecated.

**Pull request closed without merging**
