### PR TITLE
Dd 423 - Follow up fix - open cta links in new tabs.

### PR DESCRIPTION
**Pull request by teesloane**
This follows up on #6447 in which the CTA buttons did not refer back to the page. Since the behaviour seemed a little dicey (it was returning me to circleci.com) I went with just opening the button's link in a new tab.

### CODE REVIEW

**Review by devinmarieb — APPROVED** [review]

**Comment by rsylvian** [comment]
Fast! Thanks @devinmarieb

**Comment by teesloane** [comment]
> Fast! Thanks @teesloane @devinmarieb

We were faster than CI, lol!

**Review by tshen815 — APPROVED** [review]
nice!

**Review by chantelle11 — APPROVED** [review]
Nice! great turn around

**Pull request merged**
