### PR TITLE
Update docker.md - reaching services in containers

### PR DESCRIPTION
**Pull request by kkemple**
I spent a few days trying to get containers talking to the provided services. I was finally able to make it work with these simple steps. I did find a few questions about this in the forum. (I will add an answer there as well.)

### CODE REVIEW

**Comment by kimh** [comment]
Thanks for your contribution!

We explained this a bit in https://circleci.com/docs/docker/#connecting-to-services-outside-of-the-container but didn't this instruction work for you?

**Comment by kkemple** [comment]
i do understand that setting net to host can have some unusual side effects since all containers will share network with host, but i was unable to get mysql or redis to work with setting host to `0.0.0.0`. I may have missed something but I tried for quite some time. I will take another pass with `add-host` and see if i can get that to work. Either way I will update with your suggestion.

**Comment by felicianotech** [comment]
Hey @kkemple,

Did you have any luck with Kim's suggestion?

**Comment by kkemple** [comment]
I did, I missed a step in the docs my first time around, im okay with just closing this unless you think that this is still worth mentioning, sorry for delayed response, been a super hectic week!

**Comment by kimh** [comment]
@kkemple Happy to hear that it works! Since the existing step in the doc works, I'll close this PR.

**Pull request closed without merging**
