### PR TITLE
[japanese translation] "skip ci" should not be any part of commit message or the its title

### PR DESCRIPTION
**Pull request by kyontan**
# Description

It seems "skip ci" tag works if appears not in the first line of the commit body.  
To fix incorrect document, I proposed this change.

# Reasons

Our team member just tested that, and it works. (in private repository in CircleCI 2.0)

It seems Japanese version of this document says "skip ci tag can be located in any part of commit message or the its title.", and I think its correct.

https://github.com/circleci/circleci-docs/blame/05f4b70c8a534119f2b708691659d79e95e69240/jekyll/_cci2_ja/skip-build.md#L18

### CODE REVIEW

**Comment by teesloane** [comment]
Hi there @kyontan - we purposefully request users put [skip ci] in the the first line of the body as it is possible that a user's commit message could _very_ long to the point that it gets truncated when a pipeline runs; if `[skip ci]` is at the end of the body of a commit message that gets truncated, it will not properly skip. 

So, while it is indeed possible to put the [skip ci] flag throughout the body of your message, we want to officially recommend in our docs that a user hoists the flag up to the commit title or first line of the body.

I'll be closing this PR for now, but please let me know if you have additional questions.

**Comment by kyontan** [comment]
Hi @teesloane .  
Thank you for kindness explanation about the decision.
I agree placing [skip ci] in the beginning is preferred (actually, I didn't know that could be truncated).

BTW, Japanese translation describes: "[skip ci] could be any place", I think it should be fixed.  How do you think?

**Comment by teesloane** [comment]
Yes, that should be fixed. the The translation of our docs is not yet automated - if you are able to fix it, could you put up a PR?

**Comment by kyontan** [comment]
Since Japanese is my primary language, I can fix its problem.  Is it ok to update this issue? (or close this and open new one?)

**Comment by teesloane** [comment]
Yeah, that would be great! I will reopen this.

**Comment by teesloane** [comment]
@kyontan Thanks for finishing up this PR!

**Pull request merged**
