### PR TITLE
Use API 1.1 and explain retention and file size for artifacts

### LINKED ISSUE #148: Document limits on Build Artifacts size, retention, etc
RE: jekyll/_docs/build-artifacts.md

https://circleci.com/docs/build-artifacts/ doesn't mention any limits on the sizes of build artifacts (I see #122 mentions a 3GB size limit on individual artifacts; what about total size per build, or per project?), nor how long Circle promises to host the artifacts (e.g. only 3 months like (random example) [Ghost Inspector](https://ghostinspector.com/pricing/), or indefinitely but promise 6 months warning if you're gonna start taking them down, etc).

For my case I'm not actually worried about the size limit (though I would love to see it documented), just retention, especially since the filepaths are all `.../tmp/circle-artifacts.AvvFajf/...`, which isn't exactly resounding with permanence. Can I hotlink them, or should I be uploading them somewhere else? (Imgur probably)

There may be other limits worth documenting, too. (Rate limits on downloads? That's probably high enough not to be worth documenting.)

### PR DESCRIPTION
**Pull request by keybits**
Fixes #148 and #122

### CODE REVIEW

**Comment by felicianotech** [comment]
@tom The test passed, not sure why GitHub didn't get updated.

**Comment by keybits** [comment]
Rebuilding as I think this got caught by S3 outage.

**Comment by felicianotech** [comment]
@tom Did you touch Git at all to do that or just rebuilt for the CircleCI UI?

**Comment by keybits** [comment]
Just a rebuild on CircleCI - we suggest this in support when people complain the the GitHub status didn't get updated.

**Pull request merged**
