### PR TITLE
Update faq.md

### PR DESCRIPTION
**Pull request by sebastian-lerner**
# Description
A brief description of the changes.

# Reasons
A link to a GitHub and/or JIRA issue (if applicable).
Otherwise, a brief sentence about why you made these changes.

### CODE REVIEW

**Review by thomasr8 — APPROVED** [review]

**Comment by sebastian-lerner** [comment]
one more question: the section that says "How do I calculate my monthly costs?" and says "Calculate your monthly costs by finding your Storage and Network usage on the [CircleCI app](https://app.circleci.com/) by navigating to Plan > Plan Usage."

Shouldn't your monthly costs be more than just Storage and Network usage?

**Comment by devinmarieb** [comment]
@sebastian-lerner I know you just mentioned that you thought we supported two versions of windows. The hello world page still says: "Currently CircleCI supports a single Windows image: Windows Server 2019 with Visual Studio 2019." If you think we support a second image we can update the Hello World page.

To answer your question about billable usage -- that wording was gone over multiple times when the UI debacle happened and that's what was approved by the runner team. After a lot of back and forth, that is what was determined we charge for. If you have knowledge of what else we charge for (besides IP ranges soon), we can certainly discuss it, but that is a larger conversation with other teams.

**Comment by sebastian-lerner** [comment]
it just sounds odd because when I read the question, "how do i calculate my monthly costs", my first thought would be to think of my monthly credits.  not really network & storage which is one component of monthly costs.  the way it reads now makes it sound like Network & Storage are the entirety of your monthly costs?

**Comment by devinmarieb** [comment]
@sebastian-lerner Ah, yeah I see what you mean. I think that header is confusing. We can definitely change the header to say something more specific like "How do my credits relate to my cost?" or something like that?

**Comment by sebastian-lerner** [comment]
well if all we're going to mention in the body of the text is network and storage, then shouldn't the header reflect that?  like shouldn't the header be something like: "how do i calculate my monthly network and storage costs"? 

becuase a customer's monthly costs is really:

network + storage + user fees + storage + compute + DLC + IP ranges + maybe other things i'm forgetting

so if we leave the question generic and we don't want to talk about anything other than network and storage, it makes more sense to make the title of the section reflect that we're talking about network and storage i think?

**Pull request merged**
