### PR TITLE
Remove deprecated deploy step from config, update examples

### PR DESCRIPTION
**Pull request by devinmarieb**
# Description
Remove the information about the deploy step in the config ref and link to the new step/alternatives.
Adjust the examples on two pages that still used the deploy key. _Note: there is still one page referencing deploy steps for v1 of the API that needs addressing._

# Reasons
[Jira Ticket](https://circleci.atlassian.net/jira/software/projects/DOCSTEAM/boards/412?selectedIssue=DOCSTEAM-99)
Some people are still using the deploy step. By removing the information and replacing the examples, we hope to decrease the usage.

### CODE REVIEW

**Comment by devinmarieb** [comment]
@sebastian-lerner I've kept the deploy section in the config reference but removed it from the navigation and removed all the information. Instead it now links to the run step where there is a note about workflows, scheduled pipelines. I've also adjusted the Scala language page and the iOS tutorial page. Those code examples might need a second look from an engineer. For reference, these are the two live pages that still use the deploy step:
https://circleci.com/docs/2.0/language-scala/
https://circleci.com/docs/2.0/ios-tutorial/

**Comment by sebastian-lerner** [comment]
looks good to me.  is it also possible in subsequent work to make it more explicit how to replace deploy when parallelism > 1?  right now we point to examples, but is that as straightforward as we want it to be?

i dont think we should block on publishing the code snippets until eng reviews, but i can try and get someone from my team to take a look?  unless you have a different method for getting engineering to review code snippets?

**Review by sebastian-lerner — APPROVED** [review]

**Comment by sebastian-lerner** [comment]
yeah separate task makes a lot of sense.  no idea how to do it now, but agreed it's separate.

**Review by rosieyohannan — APPROVED** [review]
Looks excellent, thank you @devinmarieb! 🎉

**Comment by devinmarieb** [comment]
@sebastian-lerner circling back around to this, do you want me to get a certain developer to look at this, or have you already asked someone to take a look?

**Comment by sebastian-lerner** [comment]
Sorry, was out last week.  Let me try to get someone this week to look at it.  I don't think you need to block on a review from an engineer to push it.  Which parts specifically do we definitley want reviewed by eng? All of it? or just certain code snippets?

**Comment by devinmarieb** [comment]
@sebastian-lerner just the code samples would need to be reviewed/signed off on

**Comment by bjohnso5** [comment]
These changes all look correct to me - the one thing I'd maybe look at adding would be an example of the workflow filtering since the docs 1) mention that feature and 2) have been updated from deploy to run in some examples.

**Comment by devinmarieb** [comment]
@bjohnso5 Awesome! I'll open a new ticket for that. Thanks for checking!

**Pull request merged**
