### PR TITLE
simplify heroku deploy command

### PR DESCRIPTION
**Pull request by smart-alek**
Resolves [this JIRA issue](https://circleci.atlassian.net/browse/CIRCLE-11201) and [this JIRA issue](https://circleci.atlassian.net/browse/CIRCLE-11202).

### CODE REVIEW

**Comment by theflow** [comment]
just saw that you now recommend to deploy to Heroku this way. Not super happy that this will output the `$HEROKU_API_KEY` to the build log as part of the git push:

```
remote: -----> Launching...        
remote:        Released v646        
remote:        https://app-name.herokuapp.com/ deployed to Heroku        
remote: 
remote: Verifying deploy... done.        
To https://heroku:HERE_WOULD_BE_THE_API_KEY@git.heroku.com/app-name.git
   8ef67ff..4c90e76  4c90e76805b4d1b7097f9382ccdb396379754d7f -> master
```

is there a way to filter that out somehow?

**Comment by smart-alek** [comment]
Hey @theflow: are you defining `HEROKU_API_KEY` in the application or in `config.yml` itself?

**Comment by theflow** [comment]
I guess this is actually from git itself. And I can see in the version I'm running locally (2.13.1) it doesn't output the user:password part of the URL, where in the earlier versions it does (including the ones shipping with Debian jessie and stretch)

**Comment by smart-alek** [comment]
@theflow yep, git is being "helpful". You might be able to finagle something by using `sed`, but we did confirm that at least it's not _us_ (CircleCI). What I **will** do is add a warning around using sensitive environment variables; might actually be related to #2314.

**Pull request merged**
