### PR TITLE
Update configuration-reference.md

### PR DESCRIPTION
**Pull request by mitz418**
Remove a few sentences because now Free plan users can use DLC.

# Description

Remove a few sentences that say DLC is only for a paid plan because now Free plan users can use DLC.

### CODE REVIEW

**Review by thomasr8 — APPROVED** [review]
Looks good 👍

**Comment by mitz418** [comment]
Thank you @thomasr8 for your prompt review! Just in case, I would like to wait for @ogii 's check to merge this PR, who I consulted about this change :)

**Review by thomasr8 — APPROVED** [review]
Looks good! 👍

**Review by ogii — APPROVED** [review]
Looks fine!

**Pull request merged**
