### PR TITLE
[DD-450] Getting Started Experiment Boilerplate

### PR DESCRIPTION
**Pull request by tshen815**
Ticket: [DD-450](https://circleci.atlassian.net/browse/DD-450)
[Optimizely](https://app.optimizely.com/v2/projects/16812830475/experiments/21268663100/variations)
[Preview](http://circleci-doc-preview.s3-website-us-east-1.amazonaws.com/DD-450/getting-started-experiment-boilerplate-preview/)

⚠️ **NOTE**: We will merge this PR when ready to start running this experiment

# Changes

- combine work done in all PRs related to epic
- store experiment logic in `gettingStartedGuide`
- import experiment to app
- import image assets for experiment
- implement styles need for experiment  

# Description
For this segment of the Getting Started experiment epic we are just creating and setting up the experiment for our users. We will need to create the feature and experiment in Optimizely and add the experiment file to our `js/experiments/` directory.

# Considerations
This PR is the culmination of the [Getting Started experiment epic](https://circleci.atlassian.net/browse/DD-449) and contains the work from these past PRs:
1.  #6650 
2.  #6564
3.  #6556
4.  #6567
5.  #6591
6. #6644

# Amplitude Events and Properties

1. `clicked-on-getting-started-guide-link`
- `linkText`
- `linkHref`
- `linkIndexOnPage`
- `page`

2. `clicked-landing-page-badge`
- `badgeText`
- `badgeHref`

3. `docs-getting-started-observed`
- `sectionTitle`
- `sectionIndex`
- `page`

# Demo
**From preview link:**

https://user-images.githubusercontent.com/57234605/163037708-5d1bbafc-ddb3-40cc-94e1-c76615e41da4.mp4

# Figma
[Link](https://www.figma.com/file/HrgpUU2M3ED7OT0p0f99bH/Docs-Disco-Experiments?node-id=5482%3A11844)

### CODE REVIEW

**Review by rsylvian — APPROVED** [review]
LGTM 🙌 

Let's not merge it until we are actually ready to start the experiment though otherwise we will start to send `Experiment Viewed` events right away

**Review by aaylacci — APPROVED** [review]
LGTM

**Review by chantelle11 — COMMENTED** [review]
Highlight on scroll seems to not work. When I scroll new sections do not highlight
Screen Shot 2022-04-19 at 6 11 14 PM

**Review by Mayuko-Sa — APPROVED** [review]

**Review by chantelle11 — APPROVED** [review]
Approving paired with @tshen815

**Comment by teesloane** [comment]
Looks great! The youtube link should have an external link icon.

- [CircleCI foundation videos](https://www.youtube.com/playlist?list=PL9GgS3TcDh8wqLRk-0mDz7purXh-sNu7r)

Great work 👍 🐯

**Pull request merged**
